### ISSUE TITLE
lmmse & igv produce artifacts on overexposed photos

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#1755]
Originally reported on Google Code with ID 1771

```
See this screenshot from a 100 % view where lmsse/igv are used for demosaicing:

1. lmsse: http://imgur.com/Li5m3XM,2WJbb0p#0
2. igv: http://imgur.com/Li5m3XM,2WJbb0p#1

As seen there, a blueish pattern can be seen, most prominent in the lmsse-case.

I cannot provide a raw file to the public (I haven't got the persons OK in the picture
to do so), but please contact me per e-mail and I'll provide one to you.

Branch: default
Version: 4.0.10.7
Changeset: a0b115669e6a
Compiler: gcc 4.6.3
Processor: undefined
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.2
Build type: release
Build flags:  -march=native -fopenmp -O3 -DNDEBUG
Link flags:   -march=native
OpenMP support: ON
MMAP support: ON

Gentoo x64

```

Reported by `johan@birkagatan.com` on 2013-03-11 10:10:30

**Comment by dimonoid** [comment]
Still not fixed. I took several photos in series using sport mode. One of the photos has completely yellow sky while for others everything is ok. Using IGV demosaicing. The exposure of all the photos is exactly the same. Not sure what is the difference between the photos.

**Comment by Thanatomanic** [comment]
@dimonoid Please show an example of the artifacts you are talking about, preferably by also providing a RAW file where the effect occurs. 
On a side note: IGV and LLMSE are demosaicers that you should primarily use on noisy images. Having a noisy image _and_ overexposed areas is pushing the limits of what can be reasonably be recovered from your image. So artifacts may be entirely unavoidable.

**Comment by dimonoid** [comment]
@Thanatomanic  I know that they should be used only on noisy images. I use Nikon p1000, and all of the photos are coming very noisy. IGV is looking the best so far after my tests. Second best is LLMSE. Will provide RAW files in the next message.

**Comment by dimonoid** [comment]
@Thanatomanic https://drive.google.com/file/d/1Ao3ESi9p_g5f8rs3jbp-uZhmZciY9DLl/view?usp=sharing

There are 2 photos with yellow sky and 1 without, but taken almost immediately within the same series as one of the photos with yellow sky.

**Comment by Thanatomanic** [comment]
@dimonoid Thanks for the samples, the artifacts are clearly visible. There is also still #5516 that, once resolved, could improve your situation as well. Edit: in fact, I'll leave this issue closed and let the solution be provided on the newer issue.

Interestingly, your two photos in the park have a magenta sky indicating a wrong white point (I'll make a separate issue for that). The IGV algorithm completely fails on that, giving yellow spots.  If you want to get white skies just turn the `Raw White Points` tool up to 1.01. Hopefully this is a temporary workaround.

However, with regards to your processing: these images are not noisy at all, they are nicely shot at ISO100. Are you by any chance using IGV and LLMSE to get a sharper result from demosaicing? If so, consider using the `Capture sharpening` tool + RCD or AMaZE demosaicing instead.

**Comment by dimonoid** [comment]
@Thanatomanic Thanks. Yes, I used Capture sharpening before, but recently realized that it is amplifying the noise too much (it is applied before denoise instead of after in the pipeline, I guess?), so I use RL deconvolution + Edges + Microcontast at threshold 40 + impulse noise reduction + normal noise reduction but only in darks. Yes, those photos are not really noisy since they are overexposed. Almost all the others are noisy as hell.

**Comment by Thanatomanic** [comment]
Whitepoint issue is fixed now

**Comment by nquantum** [comment]
I still get yellow artifact from igv although noise is notice less than lmmse. Unfortunately artifact let me no choice to choose immse instead. Uncheck auto-correction, avoid color shift in Chromatic Aberration Correction won't help also. 
This is link of raw file:
[https://drive.google.com/file/d/1u00yg2-2ljOzFcCrdfBt3R_b58MdyOSc/view?usp=sharing](url)



![1](https://user-images.githubusercontent.com/18653121/103115245-6ba4d200-4694-11eb-878e-679c7b7a58b6.jpg)

**Comment by dimonoid** [comment]
> I still get yellow artifact from igv although noise is notice less than lmmse. Unfortunately artifact let me no choice to choose immse instead. Uncheck auto-correction, avoid color shift in Chromatic Aberration Correction won't help also.
> This is link of raw file:
> [https://drive.google.com/file/d/1u00yg2-2ljOzFcCrdfBt3R_b58MdyOSc/view?usp=sharing](url)
> 
> ![1](https://user-images.githubusercontent.com/18653121/103115245-6ba4d200-4694-11eb-878e-679c7b7a58b6.jpg)

I solved this issue by manually modifying(increasing) white point settings for raw development for your camera in config file (even though it says not to modify). Please note that they will be overwritten after every Rawtherapee update.
Lmsse btw gives me less artifacts than igv.
