### ISSUE TITLE
Batch queue items not reloaded from queue.csv after restart if filenames contain non-standard characters

### ISSUE THREAD

**Issue by maxiking01** [Beep6581/RawTherapee#3131]
Steps to reproduce:
1. Add several pictures to proccessing queue
2. Restart application
3. Open queue tab
4. There is any files in batched queue

OS: Windows 10 
App version: 4.2.699. It was downloaded from rawtherapee download site from this link http://rawtherapee.com/releases_head/windows/RawTherapee_WinVista_64_4.2.699-g3c016c4_gtk3.zip

**Comment by Beep6581** [comment]
Cannot reproduce in Linux.

**Comment by adamreichold** [comment]
I can also not reproduce this on Linux, but I fear this might be related to the recent rewrite of the batch queue parser. My first guess would for the reason of a difference between Windows and Linux would be text/binary file modes and I could push
````
diff --git a/rtgui/batchqueue.cc b/rtgui/batchqueue.cc
index c7d5f87..fd2af20 100644
--- a/rtgui/batchqueue.cc
+++ b/rtgui/batchqueue.cc
@@ -217,7 +217,7 @@ bool BatchQueue::saveBatchQueue ()
 {
     const auto fileName = Glib::build_filename (options.rtdir, "batch", "queue.csv");
 
-    std::ofstream file (fileName, std::ios::trunc);
+    std::ofstream file (fileName, std::ios::binary | std::ios::trunc);
 
     if (!file.is_open ())
         return false;
@@ -256,7 +256,7 @@ bool BatchQueue::loadBatchQueue ()
 {
     const auto fileName = Glib::build_filename (options.rtdir, "batch", "queue.csv");
 
-    std::ifstream file (fileName);
+    std::ifstream file (fileName, std::ios::binary);
 
     if (file.is_open ()) {
         // Yes, it's better to get the lock for the whole file reading,
````
on a hunch, but maybe just having a look at @maxiking01's `batch/queue.csv` from RT's configuration folder (after the application has been closed with a non-empty batch queue) might be useful to understand the issue.

**Comment by heckflosse** [comment]
There is an old bug in queue handling. Dont't know if it's this one:

1) put the same image to an empty queue n times (n = 7 for example)
2) remove one of them from queue
3) close rt
4) start rt
5) look the queue
=> number of images in queue is random between 0 and 6 now

**Comment by Beep6581** [comment]
@maxiking01 could you add some images to the queue and upload your `batch/queue.csv` file using http://filebin.net/ please? This should help you find that file: http://rawpedia.rawtherapee.com/File_Paths

**Comment by maxiking01** [comment]
I added a bunch of images to the queue and the queue file existed during running, after closing and restarting RawTherapee. The file you requested is on this link http://filebin.net/2yi5ro6jyt .

**Comment by Beep6581** [comment]
The csv file existed after restarting, but the queue appeared empty after restarting, correct?

**Comment by maxiking01** [comment]
It was empty.

**Comment by Beep6581** [comment]
Polish characters in the filenames. Can you try to reproduce this using filenames which do not contain any special characters? If you cannot reproduce with normal filenames, then the problem is clear.

**Comment by maxiking01** [comment]
Ok, I've tried without polish characters and the queue is preserved after a restart.

**Comment by adamreichold** [comment]
@Beep6581 Since the problem does seem to be related to implicit text codec conversions, I would push the above patch which should have no consequences on POSIX systems but disable any implicit conversions on Windows?

**Comment by Beep6581** [comment]
@adamreichold sure

**Comment by adamreichold** [comment]
@maxiking01 I pushed what is hopefully the fix for this to RT's `master` branch. Please retest when Windows builds of version 4.2.648 or later (revision number is w.r.t. to `master` branch) become available. Thanks!

**Comment by maxiking01** [comment]
Sorry if I'm resurrecting the issue, but the problem still persists on the gtk3 branch on commit bb9c184af7a3e86aa1f1a15457fa59aab4a802e7. I check it with and without polish letters in the file path. On the first one the queue is restored and the second not.
