### ISSUE TITLE
Crash while loading Fuji XTrans files

### ISSUE THREAD

**Issue by pi99y** [Beep6581/RawTherapee#3154]
Hi, I get quite frequent crashes that seem to be caused by older pp3 files, but it's really hard to pinpoint the issue, since it's a bit "random"...

Tested on:
- OS: Windows 8.1 64bit, 8GB ram
- RT:  RawTherapee_WinVista_64_Gtk3_Debug_4.2.730.zip Changeset: f5d5083be68f7cf487a688dcab37b91455fc9e6e
- Fuji X-Pro1 XTrans RAF files

I open up a folder with a at least a few images, try to load a file and it sometimes crashes. It can either crash while still in (or returning to) "file browser" view or already in the "editing view", but seems like it always crashes while either "loading", "demosaicing" or "processing" - not later on while editing (if i can get to that stage).

It seems not to be tied to specific image since it sometimes crashes on one file, some other time on another file, but nothing really consistant.

I tried to narrow it down, but I can only say that it appears that at least two things help while reproducing:
* thumbnails of images are not yet created (It's easier to reproduce if I clear the cache before opening RT) Since this mostly happens during the thumbnails are being generated it helps to have many images in the folder - so you have more time to reproduce it. This is probably also why I can't reproduce this with a single file (that crashed before).

* images have old pp3 files present (it doesn't happen if I create new pp3's with the current RT version, although  the general "profile" I load has roughly the same preferences - since that's the one I always start with)
PP3 files in this case say "AppVersion=4.1.80 Version=321".

* it could be raf/xtrans specific (can't test other)

Most of the time it crashed I get the debug report saying "pure virtual method called, terminate called without an active exception" but not always (sometimes there is no error message in the debug window)

Also note that the "failed to fetch network locations" error you see in the screenshot pops up every time I start RT and seems not to be related to this issue.

Screenshot: https://i.imgur.com/PMbtxiM.jpg
PP3: http://filebin.net/tvof90mays
(I'm not missing any files that are referred to in a profile, just the RT version is newer)

**Comment by heckflosse** [comment]
@pi99y It's related to xtrans files. I can reproduce it in Release build of master branch. It's not related to old pp3 files (at least the crash I get).

**Comment by sguyader** [comment]
I do not seem to get this kind of problems with xtrans files from my
Fujifilm X-T1.

**Comment by heckflosse** [comment]
I can sometimes reproduce it with a X-Pro 2 dng file. Sometimes it crashes, sometimes I got black output when saving to tif (bit not when saving to jpg) and sometimes it works fine. Looking

**Comment by pi99y** [comment]
@heckflosse Great! I mean, great you can reproduce it. You're much likley to find the cause than me. Thanks for looking into it.

**Comment by heckflosse** [comment]
Unfortunately I can't reproduce it in debug build. I'll run it through valgrind

**Comment by pi99y** [comment]
For me it's also present in:
Version: 4.2.699, Changeset: 3c016c41e3654cf098947057383afa2158948a7a
Version: 4.2.674, Changeset: 676a4441a12b30b401b9df49b976e32cba7c9b36
Version: 4.2.670, Changeset: 1a9121714a3a8e04d09ca0cf0f237345a732d962
Version: 4.2.539, Changeset: 6260b472a628e1d099c2b833e2e006c90a20e875
Version: 4.2.510, Changeset: 7ef35abb57ebd3654fc9e7b3b383821a7152eb87

**Comment by pi99y** [comment]
Disabling film simulation in those pp3 files seems to "fix" it...

I "mass edited" the:
> [Film Simulation]
> Enabled=true 
to 
> [Film Simulation]
> Enabled=false
in the pp3 files and now I either cannot reproduce or it is at least much less frequent (no crash yet)... so my crash is somehow related to that...

**Comment by heckflosse** [comment]
I opened #3156 because I think the crashes I observed have a different reason than the crashes pi99y observed.

**Comment by pi99y** [comment]
I did a test:

I downloaded a PEF image and copied it 50 times, applied my usual default profile and then applied another bundled profile on top of that.
I then set about 20 different film simulations across those 50 images.
I closed RT and cleared cache.
I ran RT again and tried to crash it, I couldn't.

Then I did the same test, but I uset a single FUJI Xtrans file (50 copies of it).
Other steps were the same...
I could crash it again.

So for now it looks it could be a combination of Xtrans & film-simulation...

**Comment by pi99y** [comment]
@heckflosse Sadly, @sguyader 's  new RawTherapee_WinVista_64_Gtk3_Debug_4.2.764 Changeset: 5086c0dbb92b34c37a18e5d019c41ff755834057 didn't solve this.

Here are two new backtraces of this crash: http://filebin.net/ctjdqlr0j7/gdb2.txt and http://filebin.net/ctjdqlr0j7/gdb3.txt

Thanks.

**Comment by sguyader** [comment]
@pi99y Ingo's fix was pushed to the Master branch, so if you want to test it you should try my Master (4.2.677) build.

**Comment by pi99y** [comment]
Oh, cool, so there still is a chance! :)

**Comment by pi99y** [comment]
Unfortunately it's still the same (with Master branch: 4.2.677)... still crashes. New backtrace log: http://filebin.net/ctjdqlr0j7/gdb4.txt

**Comment by Karteileiche** [comment]
Hello!

any news about the bug? If required, i can provide raw files too which crash RT.

**Comment by heckflosse** [comment]
Please provide files :+1:

**Comment by Karteileiche** [comment]
The problem exists since i updated my XE2 to FW4.0.

I have uploaded 3 files at http://filebin.net/hv52p3oyjh . Different content but same parameters. If you need RAW with different settings please specify.

I use RT 4.2.0 with Linux Mint and with Windows 7 64bit (4.2.699, 64bit). Both quit when i want to open a file from the file manager to the edit window. The file manager itself shows all files with correct meta data.

**Comment by heckflosse** [comment]
@Karteileiche After solving the trouble with your zip (it contains a tar file with extension .RAF) I could open all three files without problems using rt 4.2.745

**Comment by Karteileiche** [comment]
Sorry for the ZIP-problem.. i just used the "compress" option in Mint/Dolphin file manager.

I did not know that there is a newer version, it is not listed at http://rawtherapee.com/downloads.
But i found the links at the discuss platform and tried. It seems to be fixed in that version.

Thanks for your Help.

**Comment by heckflosse** [comment]
@Karteileiche Ok, thank you for the report and the example files :+1:

**Comment by pi99y** [comment]
Sorry for the inactivity. I can still easily reproduce the crash (with the images I provided to @heckflosse) on the latest "master" RawTherapee version 4.2.752 b3f6f1c1b522df1b6effe04da1b69c2af354b690
But mainly on those files with old pp3s. Editing images without (or current) profiles seems totaly fine.

**Comment by heckflosse** [comment]
@pi99y I tried to reproduce the crashes with the images you provided. But all works fine here. If you have one image with the corresponding pp3 which allows to clearly reproduce the crash, please tell me.

**Comment by pi99y** [comment]
No, sorry, for me it seems it's the process of creating previews/thumbnails while trying to edit what seems to crash it. A specific SET of files. Sometimes one fine works fine, the other time it crashes...

**Comment by heckflosse** [comment]
@pi99y I don't remember. I'll try again

**Comment by candardo** [comment]
RAF files from my X-E2 firmware 4.0 crash RawTherapee on Linux (Debian sid, RT 4.2._something_) and work on Windows (W10 RT 4.2.905). Having no problems with the latest (windows) version I expected this bug to closed and filed a bug to the Debian BTS asking for a new build.

Any updates on this issue?

**Comment by Karteileiche** [comment]
@candardo 

you are right, the linux version lacks on this fix. i am also waiting for an update.

@heckflosse 
Beside the XE2 FW4.0 incompatibility, i experienced crashes several times when saving files during the edit process (saving directly form the edit window, not using the queue).

**Comment by Beep6581** [comment]
1. Trouble with a raw file? Always provide a sample raw file, use http://filebin.net/
2. Crash? http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports

**Comment by candardo** [comment]
Latest RT package downloaded from Debian Linux.

Example raw file: http://filebin.net/bgx5dbkn5c

Actions to reproduce bug: RT crashes when trying to edit files after previewing it with the File Browser tab so no PP3 file available.

console output:
```
leo@asbesto:~/Scaricati$ rawtherapee 
/home/leo/Scaricati/test/DSCF1468.RAF: Unexpected end of file
Segmentation fault
```

Download page (Debian Sid package amd64): https://packages.debian.org/sid/rawtherapee

It's not the latest version but I like to use Debian package when possible. Of course you're not supposed to fix an old version. I filed a bug against the Debian package asking to provide a newer build since I 4.2.905 on Windows works fine.

From settings|info:
```
Branch: default
Version: 4.2.0
Changeset: c81d9026d25c
Compiler: cc 5.3.1
Processor: undefined
System: Linux
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: Release
Build flags: -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -std=c++11 -Wdate-time -D_FORTIFY_SOURCE=2   -fopenmp -Werror=unknown-pragmas -O3 -DNDEBUG
Link flags:  -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
OpenMP support: ON
MMAP support: ON
```

**Comment by Beep6581** [comment]
No crash here, DSCF1468.RAF opens fine and applying Auto-Levels works.
Tested in gtk3 tip (4.2.942 56af7e88)

**Comment by candardo** [comment]
I was not reporting a bug here. I was looking for a relevant upstream bug to point the Debian maintainer to. It was not obvious at all that the problem stems from a particular camera firmware version.

I only asked why is this issue still open since  it looks like it's fixed both on Windows and Linux with the latest version.

**Comment by Beep6581** [comment]
Closing as fixed.

**Comment by pi99y** [comment]
This (see my posts above) is NOT fixed, crashes consistently also with RawTherapee4.2.814 as it did with the previous builds.

**Comment by Beep6581** [comment]
@pi99y can you still reproduce the crash using the new Hald CLUT code from May 1? If you don't compile yourself, keep an eye on this link, I hope @sguyader can provide a new build:
https://discuss.pixls.us/t/new-windows-builds/615/198?u=morgan_hardwood

If you can still reproduce the crash in that version, please provide sample raw file(s) with sample pp3(s) with which to reproduce, along with a new stack backtrace, then it will make sense to re-open this issue, or to open a new issue. If you do, please click on "Administration interface" in http://filebin.net/ and set the lifetime to 1 year so the uploads don't expire so quickly.

**Comment by pi99y** [comment]
OK, I'll wait for @sguyader 's new build or (if he won't be able to make one in a few days) I'll do it with the 32bit build.

Also are the newer debug builds now working OK? I remember (from IRC I think) something about (windows) backtraces not being ~descriptive enough - see the debate here #3231 Are the new builds now compiled with the correct "settings"? Since the debug builds are really slow for me I'd hate to "waste" the time if it's not helpfull..
Thanks

**Comment by Beep6581** [comment]
Debug builds are always descriptive. The `-DWITH_SAN=thread` option is something extra. @heckflosse @adamreichold do you think a build with the thread sanitizer would help?

**Comment by sguyader** [comment]
Ok I'll make new builds (it's going to take some time, I make the Windows builds in a Windows virtual machine which shares the machine resources with the host system, on an aging laptop...)
Should I make only Gtk3 builds, or should I make builds from Master branch too?
I'll try the ``-DWITH_SAN=thread`` option fro the Debug build, but last time I tried it didn't work.

**Comment by Beep6581** [comment]
Well, I will only upload gtk3 ones. As for the usefulness of sanitization of the debug build, @heckflosse and @adamreichold should decide.

**Comment by heckflosse** [comment]
@Beep6581 @sguyader IIRC sanitizers still don't work with windows builds

**Comment by sguyader** [comment]
Here's a link to Gtk3 Release and Debug builds:
http://filebin.net/jj9l7sgaij

**Comment by pi99y** [comment]
@sguyader Are these two new builds by any chance not compiled right? Now it crashes every time and the gdb log inludes your username:

> Program received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 4472.0xd90]
> 0x0000000000b60896 in LUT<float>::operator[] (this=0x166af270,
>  index=-nan(0x400000))
>  at C:/msys64/home/sguyader/rtrepo-gtk3/rtengine/LUT.h:453
>  453 C:/msys64/home/sguyader/rtrepo-gtk3/rtengine/LUT.h: No such file or directory.

**Comment by Beep6581** [comment]
I uploaded those builds to the website. Would be good if someone else could confirm the problem so I take them down ASAP if they're faulty.

**Comment by Floessie** [comment]
@Beep6581 I wouldn't generally advocate sanitizers for the debug build: While debug builds are big and slow, instrumented builds are even bigger and slower. I've got no experience with TSan, but finding subtle races ("heisenbugs") sometimes is even impossible with debug builds, as they behave quite differently from release builds when it comes to timing issues. IMHO having backtraces is enough most of the times to catch them. But a sanitizer build to nail down a specific problem like this one would definitly help.

> Now it crashes every time and the gdb log includes your username.

@pi99y That's normal. But a full backtrace is what's needed here. Especially the next frame, the caller who calls `LUT<float>::operator[]` with `-nan`, is of interest.

> Would be good if someone else could confirm the problem so I take them down ASAP if they're faulty.

@Beep6581 Apart from the fact, that I'm not on Windows, I'll be offline this evening, sorry.

**Comment by heckflosse** [comment]
@Beep6581 I tested the Release build from @sguyader. I opened some RAF files. Can't confirm the crashes.

**Comment by pi99y** [comment]
@heckflosse Can you try reproducing the crash a a RAF that has an existing pp3 and uses film simulation please

**Comment by Beep6581** [comment]
Great, the builds stay up.

@pi99y 

> If you can still reproduce the crash using the new version, please provide sample raw file(s) with sample pp3(s) with which to reproduce, along with a new stack backtrace, then it will make sense to re-open this issue, or to open a new issue. If you do, please click on "Administration interface" in http://filebin.net/ and set the lifetime to 1 year so the uploads don't expire so quickly.

The backtrace you pasted lacks the important part, see step 5 onwards: http://rawpedia.rawtherapee.com/How_to_write_useful_bug_reports#Step_by_step

Please supply the minimum number of sample raw(s) + PP3(s) needed to reproduce this. We can figure out the required Hald CLUT folder structure from the PP3(s), as long as you used the Hald CLUTs from the "RawTherapee Film Simulation Collection".

**Comment by sguyader** [comment]
I can reproduce it, I think, with the new build. It occasionally crashes with some files (it never crashes my files form my X-T1 though). I'll try to make backtraces.

**Comment by pi99y** [comment]
@Beep6581 The backtrace was done with all the steps but windows gdb has allways crashed for me after the "thread apply all bt full" which I guess was the reason for the "sanitation" version as noted in #3231 Please note that in #3231 @sguyader did provide one build with the added option (I'm guessing) which didn't crash the gdb.

I did use the  "RawTherapee Film Simulation Collection".

I'll post the RAF files shortly here: _________link here____________

**Comment by sguyader** [comment]
No my build wasn't sanitized, just as Ingo said thread sanitization fails on Windows (I saw it's supported only on Lunix 64 bits).

**Comment by heckflosse** [comment]
@sguyader Sebastien, I just found a buffer overrun. As you can reproduce the crash, can you try with [this patch](https://gist.github.com/heckflosse/dd443924942184bb66eaa318fe567716) please?

**Comment by pi99y** [comment]
Now I have uploaded the files (in my previous post above). 
What else can I do?

**Comment by sguyader** [comment]
Ingo I'll try your patch. In the mean time, here's a backtrace of a crash, from an X-T1 file (source DPReviw), no previous pp3, starting from default processing profile, and just activating Film Simulation and loading a HALDClut:

http://pastebin.com/cdm1LYdJ

**Comment by sguyader** [comment]
@heckflosse Ingo I applied your patch, but I still get the same knid of crash. by the way, at the end of generating the full backtrace, gdb.exe itself crashes.
New backtrace: http://pastebin.com/jhmT7pMs

**Comment by sguyader** [comment]
I just tried with the amsterdam.pef boat raw file, and it crashes too as soon as I select a HaldCLUT (again, no previous pp3, staring from default processing profile, nothing changed, only the Film Simulation turned on and a Clut selected).

**Comment by heckflosse** [comment]
I just pushed the fix to master branch

**Comment by heckflosse** [comment]
@sguyader DrSlony merged the fix to gtk3

**Comment by sguyader** [comment]
If the fix is just from your last patch, I'm afraid it's still not the cure for this problem...
I'm trying on another computer, and what I see is that it's not happening on all x-trans files. It crashes on an old X-T1 file (from DPReview), but not one my own X-T1 files (mine probably has more recent firmware) nor on an X-Pro2 file.

**Comment by pi99y** [comment]
@sguyader Can you maybe provide a new build so I can test aswell or test the files I posted above?

**Comment by heckflosse** [comment]
@sguyader Ok, but the fix was needed anyway.

**Comment by heckflosse** [comment]
@sguyader [this one](https://github.com/Beep6581/RawTherapee/commit/9622bbc2ba8a5c9f78cbe528f23575e0c60705f8)

**Comment by sguyader** [comment]
@heckflosse no I applied just [this overrunfix patch](https://gist.github.com/heckflosse/dd443924942184bb66eaa318fe567716), I didn't see the other one.
I'll make some new builds, but it will be in a couple hours.

[Here](http://filebin.net/m8uoy3d7yw)'s a set of 3 files which: the XPRO2-ImagingRes.RAF and the XT1-sguyader don't seem make RT crash, only XT1-DPReview.RAF makes it crash on 2 Windows 7 computers here, even with the "overrunfix" patch I applied.

**Comment by heckflosse** [comment]
@sguyader The clutstore.cc fix should fix the bug

**Comment by sguyader** [comment]
Ok, sorry I have to go, I'll make new builds as soon as I can.

**Comment by sguyader** [comment]
Here are the new Gtk3 builds for testing:
http://filebin.net/q6lfpl35js

**Comment by heckflosse** [comment]
@sguyader Sebastien, thanks a lot :+1:

**Comment by pi99y** [comment]
For me the latest 4.2.971 build crashes in the same way as before - as soon as I navigate to the directory containing two pictures I posted above / previously (repeated link: http://filebin.net/egkvka7twv/RTtest.zip ).

Here's the backtrace (with all the steps but gdb crashes as per usual): http://filebin.net/dfpdykc6d9/RTlog20160504.txt

**Comment by Floessie** [comment]
@heckflosse Damn, I'm really sorry for this stupid bug (missing a :facepalm: symbol here). And I'm also sorry for not having the time to investigate last evening, as I should have found it. Gosh!

**Comment by heckflosse** [comment]
@pi99y After setting max. number of cached cluts to 1 in preferences I can sometimes reproduce the crash with your example files.
@Floessie May that crash be caused by deleting currently used clut from cache when there's not enough room in cache. In file browser there are a lot of working threads.

**Comment by pi99y** [comment]
@heckflosse backtrace after cached cluts set to 1: http://filebin.net/dfpdykc6d9/RTcrash20160504b.txt

**Comment by Floessie** [comment]
@heckflosse Hmm, `std::shared_ptr<>` is defined to be thread safe, so even if it's discarded, it should still be valid until the last instance is gone. Btw., doesn't pi99y's backtraces show, that the `-NaN` is in `r`, `g`, and `b` in `improcfun.cc:3557`, long before HaldCLUT is applied on that tile? I was not yet able to reproduce the crash, but will try with cache limited to 1.

**Comment by heckflosse** [comment]
@Floessie Yes, it's long before CLUT is applied. In IRC with pi99y we tried with cache size > 2 and just 2 files in a folder. That also crashed, so we can rule out the cache handling as a possible reason.
It's very hard to reproduce the crash at my system. With the files from pi99y I could reproduce it at least 10 times in debug and release build (but only with cache size = 1). Now I can't reproduce it anymore, though I didn't change anything...

**Comment by Floessie** [comment]
@heckflosse I've tried to reproduce it with pi99y's files on Debian Stretch AMD64 and PPC32 but can neither. TSan on AMD64 spits out a lot of races, mostly in thumbnail processing. I could not determine the source of that yet, but it might be a hint. ASan is okay. Funny enough, the backtraces root in `Thumbnail::upgradeThumbImage()`. Coincidence?

**Comment by Floessie** [comment]
@heckflosse An anomaly I see here is when entering a directory with only the two RAFs from pi99y, whose thumbnails where not yet cached, and (quickly) selecting the second image, I have both thumbnails on top of the editor view, but the first one (with the window) has only half its width! Switching to filebrowser and back repairs that.

HTH,
Flössie

**Comment by sguyader** [comment]
@heckflosse @Floessie have either of you tried one of the raw files I upload [here](http://filebin.net/m8uoy3d7yw)?
With these 3 files, I consistently get a crashes only with XT1-DPReview.RAF, and no crash with the other 2 files. Consistent also among 2 computers running Windows 7 64 bits (one native, one in Virtualbox).

@Floessie I also noticed in a couple occurences that the tumbnail didn't refresh correctly on one (other) problematic file. One time the thumbnail was only scrambled pixels, later it was not rotated (the image was shot in vertical position).

**Comment by Floessie** [comment]
@sguyader Now I have: No problem or crash with your files on Linux, even with HaldCLUT applied and cache size 1 (although I think that was a red herring due to my daft bug, kindly found and fixed by Ingo). Sorry for the trouble last evening.

**Comment by heckflosse** [comment]
@Floessie [this condition](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/improcfun.cc#L4361) looks wrong to me and could lead to overruns. Or do I miss some thing?

**Comment by heckflosse** [comment]
Shouldn't that be
`if (!(std::min(TS, tW - jstart) & 3))`
instead?

**Comment by heckflosse** [comment]
@Floessie May I suggest to use [this pattern](https://gist.github.com/heckflosse/eefdf4fcb94bd021e840e90cee4359fc) for sse border cases?

**Comment by heckflosse** [comment]
@sguyader What's your thumb size in preferences?

**Comment by sguyader** [comment]
@heckflosse 250 pixels

**Comment by pi99y** [comment]
My thumbnail size is set to 250px too.

**Comment by Floessie** [comment]
@heckflosse You are of course right! It's masked the wrong way. I'll fix it with your suggested pattern.

**Comment by heckflosse** [comment]
@sguyader Does it also crash with thumb size 112 or 224?
@Floessie Great! Thank you :+1:

**Comment by Floessie** [comment]
@heckflosse [Here](https://github.com/Beep6581/RawTherapee/pull/3276) it is.

**Comment by heckflosse** [comment]
@Floessie Already merged into master. Thank you :)
@Beep6581 Can you merge it into gtk3 branch please?

**Comment by Floessie** [comment]
@heckflosse So I could have skipped the PR. Great!

**Comment by heckflosse** [comment]
@Floessie No, the PR was good as it allowed me to merge it with a button click :)

**Comment by pi99y** [comment]
When there's a build I'll be happy to test it and report my findings.

**Comment by sguyader** [comment]
Is the bug only in the Gtk3 builds? If not I can make Master builds while waiting for the branch to be merged into Htk3 branch.

**Comment by heckflosse** [comment]
@sguyader No, the bug is in master and gtk3, but currently fixed only in master

**Comment by Beep6581** [comment]
And now merged into gtk3.

**Comment by sguyader** [comment]
New builds are here: http://filebin.net/gic1s01q9n

**Comment by pi99y** [comment]
Tested: gtk3 4.2.974
Changeset: ab0783e6fe784c9854fdac1205dfbdb9cfe8bee2

For me nothing has changed - exactly the same crash upon entering the directory with the two pictures and pp3 files. I cleared the cache before testing.

new backtrace: http://filebin.net/zhn7qvkblw/rtcrash20160505.txt

**Comment by pi99y** [comment]
Would it help if I live boot into ~ubuntu 16.04 and run the linux debug build you prepare for me? Would that backtrace be better? (I can do it tommorow morning / in cca 8 hours)

**Comment by sguyader** [comment]
My buolds are for windows only

**Comment by heckflosse** [comment]
@sguyader Sébastien, can you also still reproduce the crash?

**Comment by sguyader** [comment]
@heckflosse yes I got a crash again. This time it was again with ``amsterdam.PEF`` file.
Here's the output from console running th edebug build:
`Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 3812.0xadc]
0x0000000000b6bdc6 in LUT<float>::operator[] (this=0xd1a1c70,
    index=-nan(0x400000))
    at C:/msys64/home/sguyader/rtrepo-gtk2/rtengine/LUT.h:453
453             T p1 = data[idx];`

You can find a backtrace here: http://pastebin.com/FNFaxE1r

**Comment by heckflosse** [comment]
@sguyader Ok, does it still crash only when using CLUT?

**Comment by sguyader** [comment]
I think so. I didn't test a lot of things though because it's quite slow in the virtual machine. I'll try some filters.

**Comment by heckflosse** [comment]
@sguyader Thanks for your effort. With the last fix we at least ruled out another possible reason for the crash.
@Floessie Do you have an idea how to proceed with this case?

**Comment by sguyader** [comment]
@heckflosse I used another gdb.exe (so-called snapshot from www.equation.com) and this one the debugger apparently didn't crash, so maybe the following backtrace is actually complete: http://pastebin.com/BHniM7nk

After ``amsterdam.PEF`` was opened, FilmSimulation was turned on, and the crash occurred upon selecting a HaldCLUT.

If I open this file and don't use Film Simulation, I can use many folders and nothing seems to lead to a crash.

**Comment by pi99y** [comment]
Here's my backtrace with the new gdb that doesn't crash that @sguyader provided:
http://filebin.net/l1dw8o375e/RTcrash_pi99y_20160506.txt

(gtk3, 4.2.974, ab0783e6fe784c9854fdac1205dfbdb9cfe8bee2)

**Comment by heckflosse** [comment]
I can reproduce the crash now with 'generic' build, but not with 'native' build. Maybe that's also the reason it doesn't crash at @Floessie . Making 'generic' Debug build now...

**Comment by sguyader** [comment]
Guys, if gdb crashes before the end of making the backtrace, please try the following gdb.exe, it's outdated but seems to not crash:
ftp://ftp.equation.com/gdb/snapshot/64/gdb.exe

If you get complete backtrace with this older gdb.exe, maybe I'll include this one in the upcoming debug builds.

**Comment by heckflosse** [comment]
No more backtraces please. After being able to reproduce the crash, it's almost fixed. I'll push later

**Comment by heckflosse** [comment]
@Floessie I made a brute force solution for [this case](https://github.com/Beep6581/RawTherapee/blob/master/rtengine/clutstore.cc#L86). Maybe you find a better one which also does not crash generic builds.

**Comment by Beep6581** [comment]
@sguyader I merged master into gtk3. Tomorrow I'm leaving for two weeks, so this is the last opportunity to get a fixed build out there. If you could make new builds today or tomorrow early morning I could still upload them.

**Comment by Beep6581** [comment]
(Merge in progress, I'm running a test compilation, will push within 10 minutes)

**Comment by sguyader** [comment]
@Beep6581 I'm already compiling, I should be able to have the new builds uploaded in a couple hours.

**Comment by sguyader** [comment]
Here are the brand new builds: http://filebin.net/ca874j9t7m

**Comment by pi99y** [comment]
@sguyader Can't download - says "tag you are trying to access has expired"

**Comment by heckflosse** [comment]
@Floessie After the dust has settled we can change the access to r(gb)temp again to aligned access. I made them unaligned during the process to solve this issue, but as the r(gb)temp buffers in rgbproc are already correctly aligned that isn't really necessary

**Comment by Beep6581** [comment]
Same for me - can't download.

**Comment by sguyader** [comment]
Sorry, here's a new link: http://filebin.net/047o539v44

It seems that if I try to access to the link before the upload is finished, it becomes unavailable.

**Comment by heckflosse** [comment]
@sguyader Sébastien, thank you very much for the new builds :+1:

**Comment by CharlesRT2** [comment]
Looks good: I installed the RawTherapee_WinVista_Gtk3_Release_64_4.2.976 build, opened RT on a folder containing a RAF file and a film simulation .pp3, and with the HaldCLUT folder in the RT program folder. Opened the RAF and did a few edits -- no problems.

**Comment by Floessie** [comment]
@heckflosse I'll be back from my trip on monday. Here I have only limited Wifi and can hardly follow the discusssion. I'll have a look at it on monday, and see how I can reproduce it with a generic debug build and then start off with your work and try to figure out what speedup we've lost. Was the `ALIGNED16` relevant for the Windows build, or isn't that a NOP on Windows? If we can load and store aligned again, that would be nice. If I can make it crash with a generic build, I can test that. Thanks for all your investigations.

pi99y started this issue long before we optimized the HaldCLUT code. Do you think the problem was always related to the buffer overrun in the original code? You know the `i + 1` access during interpolation?

**Comment by pi99y** [comment]
Congratulations guys! I wasn't able to reproduce the recent bug again with the new builds - gtk3 or master. Also I tested the files from the original problem (first post) and it didn't crash, so that problem was tightly related if not the same.
Thanks!

**Comment by CharlesRT2** [comment]
> "pi99y started this issue long before we optimized the HaldCLUT code. Do you think the problem was always related to the buffer overrun in the original code? You know the i + 1 access during interpolation?"

It might bear on this point that when I reported a related issue in [(https://github.com/Beep6581/RawTherapee/issues/3277)] , the HaldCLUT folder in my RT program folder was from summer 2014.

**Comment by pi99y** [comment]
I had the latest HaldCLUT when I first reported this.

**Comment by heckflosse** [comment]
@Floessie I'm quite sure the +1 buffer overrun was the reason for the crashes with old code. With new code we had a +3 overrun with SSE2 code and a +7 overrun with SSE4.1 code. But the main reason for the crash was that the compiler generated aligned loads in the getClutValue(..) function but 16-byte aligned access is impossible when loading 16bit quadrupels. For whatever reason for native builds on my machine (and most likely on your machine too) it generated unaligned loads and all worked fine.

**Comment by heckflosse** [comment]
@Floessie The ALIGNED16 define is a NOP for Win32 builds and the LVF(STVF) are mapped to their unaligned variants for Win32 builds too. For Win64 builds and non Windows builds they take effect and reintroducing them into clut code should not harm.

**Comment by Floessie** [comment]
@heckflosse Hm, I still cannot make it crash with `-DPROC_TARGET_NUMBER=1` and `-DCMAKE_BUILD_TYPE=debug`. Anything else I can try? My GCC is 5.3.1 on Debian Stretch AMD64.

This is what I get with 9622bbc:
```
0000000000e534da <(anonymous namespace)::getClutValue(AlignedBuffer<unsigned short> const&, unsigned long)>:
  e534da:       55                      push   %rbp
  e534db:       48 89 e5                mov    %rsp,%rbp
  e534de:       48 89 7d a8             mov    %rdi,-0x58(%rbp)
  e534e2:       48 89 75 a0             mov    %rsi,-0x60(%rbp)
  e534e6:       48 8b 45 a8             mov    -0x58(%rbp),%rax
  e534ea:       48 8b 40 20             mov    0x20(%rax),%rax
  e534ee:       48 8b 55 a0             mov    -0x60(%rbp),%rdx
  e534f2:       48 01 d2                add    %rdx,%rdx
  e534f5:       48 01 d0                add    %rdx,%rax
  e534f8:       48 8b 00                mov    (%rax),%rax
  e534fb:       48 89 45 f8             mov    %rax,-0x8(%rbp)
  e534ff:       0f 6f 45 f8             movq   -0x8(%rbp),%mm0
  e53503:       0f ef c9                pxor   %mm1,%mm1
  e53506:       0f 61 c1                punpcklwd %mm1,%mm0
  e53509:       0f 7f 45 f0             movq   %mm0,-0x10(%rbp)
  e5350d:       0f 6f 45 f8             movq   -0x8(%rbp),%mm0
  e53511:       0f ef c9                pxor   %mm1,%mm1
  e53514:       0f 69 c1                punpckhwd %mm1,%mm0
  e53517:       0f 7f 45 e8             movq   %mm0,-0x18(%rbp)
  e5351b:       66 0f ef c0             pxor   %xmm0,%xmm0
  e5351f:       0f 29 45 d0             movaps %xmm0,-0x30(%rbp)
  e53523:       0f 28 45 d0             movaps -0x30(%rbp),%xmm0
  e53527:       0f 2a 45 f0             cvtpi2ps -0x10(%rbp),%xmm0
  e5352b:       0f 29 45 c0             movaps %xmm0,-0x40(%rbp)
  e5352f:       0f 28 45 c0             movaps -0x40(%rbp),%xmm0
  e53533:       0f 2a 45 e8             cvtpi2ps -0x18(%rbp),%xmm0
  e53537:       0f 29 45 b0             movaps %xmm0,-0x50(%rbp)
  e5353b:       0f 28 45 c0             movaps -0x40(%rbp),%xmm0
  e5353f:       0f 16 45 b0             movhps -0x50(%rbp),%xmm0
  e53543:       90                      nop
  e53544:       5d                      pop    %rbp
  e53545:       c3                      retq   
```

**Comment by heckflosse** [comment]
@Floessie Here's what I get with gcc 5.3.0 `-DCMAKE_BUILD_TYPE=debug` , `-DPROC_TARGET_NUMBER=1` and 9622bbc on Win64.

```
0000000000000803 <_ZN12_GLOBAL__N_112getClutValueERK13AlignedBufferItEy>:
     803:	55                   	push   %rbp
     804:	48 89 e5             	mov    %rsp,%rbp
     807:	48 83 ec 20          	sub    $0x20,%rsp
     80b:	48 89 4d 10          	mov    %rcx,0x10(%rbp)
     80f:	48 89 55 18          	mov    %rdx,0x18(%rbp)
     813:	48 8b 45 10          	mov    0x10(%rbp),%rax
     817:	48 8b 40 20          	mov    0x20(%rax),%rax
     81b:	48 8b 55 18          	mov    0x18(%rbp),%rdx
     81f:	48 01 d2             	add    %rdx,%rdx
     822:	48 01 d0             	add    %rdx,%rax
     825:	66 0f 6f 00          	movdqa (%rax),%xmm0
     829:	0f 29 45 f0          	movaps %xmm0,-0x10(%rbp)
     82d:	66 0f 6f 45 f0       	movdqa -0x10(%rbp),%xmm0
     832:	66 0f 38 33 c0       	pmovzxwd %xmm0,%xmm0
     837:	0f 29 45 e0          	movaps %xmm0,-0x20(%rbp)
     83b:	66 0f 6f 45 e0       	movdqa -0x20(%rbp),%xmm0
     840:	0f 5b c0             	cvtdq2ps %xmm0,%xmm0
     843:	90                   	nop
     844:	48 83 c4 20          	add    $0x20,%rsp
     848:	5d                   	pop    %rbp
     849:	c3                   	retq
```

**Comment by heckflosse** [comment]
@Floessie We always need 2 consecutive quad words. The first of them is always 16 byte aligned. Why don't we change the getClutValue function this way? Code is incomplete and not tested, just to show you the idea in the SSE4_1 part. I don't know whether this is doable also for the non SSE4_1 part, because I don't know much about mmx:

```
#ifdef __SSE2__
vfloat2 getClutValues(const AlignedBuffer<std::uint16_t>& clut_image, size_t index)
{
#ifdef __SSE4_1__
    vint temp = _mm_load_si128(reinterpret_cast<const __m128i*>(clut_image.data + index));
    vfloat2 result;
    result.x = _mm_cvtepi32_ps(_mm_cvtepu16_epi32(temp);
    temp = _mm_shuffle_epi32(temp,_MM_SHUFFLE(3, 2, 3, 2));
    result.y = _mm_cvtepi32_ps(_mm_cvtepu16_epi32(temp);
    return result;
    //return _mm_cvtepi32_ps(_mm_cvtepu16_epi32(_mm_loadu_si128(reinterpret_cast<const __m128i*>(clut_image.data + index))));
#else
    return _mm_set_ps(clut_image.data[index + 3], clut_image.data[index + 2], clut_image.data[index + 1], clut_image.data[index]);
#endif
}
#endif
```

**Comment by heckflosse** [comment]
I deleted my last post, because I was wrong about the 'always 16 Byte aligned'

**Comment by heckflosse** [comment]
@Floessie Here's my objdump from 9622bbc without SSE4.1
```
0000000000000803 <_ZN12_GLOBAL__N_112getClutValueERK13AlignedBufferItEy>:
     803:	55                   	push   %rbp
     804:	48 89 e5             	mov    %rsp,%rbp
     807:	48 83 ec 50          	sub    $0x50,%rsp
     80b:	48 89 4d 10          	mov    %rcx,0x10(%rbp)
     80f:	48 89 55 18          	mov    %rdx,0x18(%rbp)
     813:	48 8b 45 10          	mov    0x10(%rbp),%rax
     817:	48 8b 40 20          	mov    0x20(%rax),%rax
     81b:	48 8b 55 18          	mov    0x18(%rbp),%rdx
     81f:	48 01 d2             	add    %rdx,%rdx
     822:	48 01 d0             	add    %rdx,%rax
     825:	48 8b 00             	mov    (%rax),%rax
     828:	48 89 45 f8          	mov    %rax,-0x8(%rbp)
     82c:	0f 6f 45 f8          	movq   -0x8(%rbp),%mm0
     830:	0f ef c9             	pxor   %mm1,%mm1
     833:	0f 61 c1             	punpcklwd %mm1,%mm0
     836:	0f 7f 45 f0          	movq   %mm0,-0x10(%rbp)
     83a:	0f 6f 45 f8          	movq   -0x8(%rbp),%mm0
     83e:	0f ef c9             	pxor   %mm1,%mm1
     841:	0f 69 c1             	punpckhwd %mm1,%mm0
     844:	0f 7f 45 e8          	movq   %mm0,-0x18(%rbp)
     848:	66 0f ef c0          	pxor   %xmm0,%xmm0
     84c:	0f 29 45 d0          	movaps %xmm0,-0x30(%rbp)
     850:	0f 28 45 d0          	movaps -0x30(%rbp),%xmm0
     854:	0f 2a 45 f0          	cvtpi2ps -0x10(%rbp),%xmm0
     858:	0f 29 45 c0          	movaps %xmm0,-0x40(%rbp)
     85c:	0f 28 45 c0          	movaps -0x40(%rbp),%xmm0
     860:	0f 2a 45 e8          	cvtpi2ps -0x18(%rbp),%xmm0
     864:	0f 29 45 b0          	movaps %xmm0,-0x50(%rbp)
     868:	0f 28 45 c0          	movaps -0x40(%rbp),%xmm0
     86c:	0f 16 45 b0          	movhps -0x50(%rbp),%xmm0
     870:	90                   	nop
     871:	48 83 c4 50          	add    $0x50,%rsp
     875:	5d                   	pop    %rbp
     876:	c3                   	retq   
     877:	90                   	nop
```
This still crashes here

**Comment by Floessie** [comment]
@heckflosse That looks basically the same as mine. Nice. Or not, considering those
```
     84c:   0f 29 45 d0             movaps %xmm0,-0x30(%rbp)
     850:   0f 28 45 d0             movaps -0x30(%rbp),%xmm0
```
redundant loads and stores (or am I missing something?). I forgot to mention, that I was running my test on Qemu, I'll retest it on real hardware this evening. The SSE 4.1 version definitly shines with compactness. :)

**Comment by heckflosse** [comment]
@Floessie I guess the redundant loads ans stores are caused by debug build

**Comment by Floessie** [comment]
@heckflosse When you write 
> This still crashes here
you mean "on Windows"? I've now tested it on real hardware and it still doesn't crash. I'm stumped.

**Comment by heckflosse** [comment]
@Floessie Yes, it crashes on Windows (the commit you mentioned, not the master branch). I'm stumped too...

**Comment by heckflosse** [comment]
@Floessie What do you think about changing vfloat getclutvalue(index) to vfloat2 getclutvalues(index)?
We always need two consecutive quad words. This way we could load them with one unaligned load and shuffle them into the vfloat2.

**Comment by Floessie** [comment]
@heckflosse Did `return _mm_cvtpu16_ps(*reinterpret_cast<const __m64*>(clut_image.data + index));` in `getClutValue()` really fail? It generates the following code in a generic build:
```
  aa285c:       43 0f 6f 0c 62          movq   (%r10,%r12,2),%mm1
  aa2861:       0f 6f d1                movq   %mm1,%mm2
  aa2864:       0f 69 c8                punpckhwd %mm0,%mm1
  aa2867:       0f 61 d0                punpcklwd %mm0,%mm2
  aa286a:       0f 2a d2                cvtpi2ps %mm2,%xmm2
  aa286d:       0f 28 da                movaps %xmm2,%xmm3
  aa2870:       0f 2a d9                cvtpi2ps %mm1,%xmm3
```
And a `movq` is what we need. It should not be sensitive to alignment.

About `vfloat2`: Sounds sane. BTW: Somehow your fix made the speedup even faster: Measuring 233ms where there were 274ms before. I'll look into the `vfloat2` approach next evening.

**Comment by Floessie** [comment]
@heckflosse Which intrinsic will convert the `__m128i` as `unsigned short` to `__m128` in SSE2?

**Comment by heckflosse** [comment]
@Floessie Yes, it failed. Though I don't know why :( I'll try again...

**Comment by heckflosse** [comment]
@Floessi 

> Which intrinsic will convert the  __m128i  as  unsigned short  to  __m128  in SSE2
Yes, that's a problem for the non SSE4.1 code. Don't know :(

**Comment by Floessie** [comment]
@heckflosse Okay, I'll investigate tomorrow. :)

**Comment by heckflosse** [comment]
@Floessie great :+1:

**Comment by Floessie** [comment]
@heckflosse I've got an idea for my evening session: If we can't got the high road (`__m128i`), we'll go the low road (`__m64`) with `_mm_movepi64_pi64`, `_mm_slli_si128`, and `_mm_cvtpu16_ps`. That should be viable.

I've already started a "dedusting" branch last evening, which I will push for you to test when I'm through with the `vfloat2` conversion. I guess, we will gain some additional speed from this. :+1:

**Comment by Floessie** [comment]
@heckflosse Could you please check, if it still crashes for you?

**Comment by heckflosse** [comment]
@Floessie I just pulled your changes. Making generic build now...

**Comment by heckflosse** [comment]
@Floessie Generic Release build crashes, making Generic Debug build now...

**Comment by heckflosse** [comment]
@Floessie Sorry, tested wrong branch....

**Comment by Floessie** [comment]
@heckflosse  Phew, you like to raise the tension! :)

**Comment by heckflosse** [comment]
@Floessie dedusting... branch still crashes with generic debug build. Making further tests now...

**Comment by Floessie** [comment]
@heckflosse I not only changed `getClutValue()` but also the `STFU`s etc. in `improcfun.cc`...

**Comment by heckflosse** [comment]
@Floessie with added -msse4 flag dedusting... generic build works fine!

**Comment by Floessie** [comment]
@heckflosse So it's not the alignment but either `_mm_movepi64_pi64` (new, thus unlikely) or `_mm_cvtpu16_ps` (used before, so likely). `_mm_cvtpu16_ps` translates to multiple instructions, so your compiler might be wrong here...

**Comment by heckflosse** [comment]
@Floessie I made further tests. Crashes with Generic Release build without -msse4. Works fine with Generic Release build with -msse4.
I'll test the brute force _mm_set_ps() variant now on non -msse4 Generic build

**Comment by heckflosse** [comment]
@Floessie Brute force _mm_set_ps() variant work fine for non -msse4 Generic build

**Comment by heckflosse** [comment]
@Floessie Here's the code of _mm_cvtpu16_ps from xmmintrin.h at my system if that's of any use:
```
/* Convert the four unsigned 16-bit values in A to SPFP form.  */
extern __inline __m128 __attribute__((__gnu_inline__, __always_inline__, __artificial__))
_mm_cvtpu16_ps (__m64 __A)
{
  __v2si __hisi, __losi;
  __v4sf __zero, __ra, __rb;

  /* Convert the four words to doublewords.  */
  __losi = (__v2si) __builtin_ia32_punpcklwd ((__v4hi)__A, (__v4hi)0LL);
  __hisi = (__v2si) __builtin_ia32_punpckhwd ((__v4hi)__A, (__v4hi)0LL);

  /* Convert the doublewords to floating point two at a time.  */
  __zero = (__v4sf) _mm_setzero_ps ();
  __ra = __builtin_ia32_cvtpi2ps (__zero, __losi);
  __rb = __builtin_ia32_cvtpi2ps (__ra, __hisi);

  return (__m128) __builtin_ia32_movlhps (__ra, __rb);
}
```

**Comment by Floessie** [comment]
@heckflosse GCC 5.3.1 has exactly the same code. I've got a clang 3.5.0 version here (annotations by me), which is a bit different, and could be tried by pasting it as `mm_cvtpu16_ps` right in front of `getClutValues()`:
```
static __inline__ __m128 __attribute__((__always_inline__, __nodebug__))
_mm_cvtpu16_ps(__m64 __a)
{
  __m64 __b, __c;
  __m128 __r;

  __b = _mm_setzero_si64(); // MMX
  __c = _mm_unpackhi_pi16(__a, __b); // MMX
  __r = _mm_setzero_ps(); // SSE
  __r = _mm_cvtpi32_ps(__r, __c); // SSE
  __r = _mm_movelh_ps(__r, __r); // SSE
  __c = _mm_unpacklo_pi16(__a, __b); // MMX
  __r = _mm_cvtpi32_ps(__r, __c); // SSE

  return __r;
}
```
I have no idea, what's wrong with your compiler and `_mm_cvtpu16_ps`. Maybe we are on the wrong track, don't know. The last thing I would try is inline assembly, but only when worse comes to worse.

**Comment by Floessie** [comment]
@heckflosse Don't know how old and still relevant [this](http://www.peterstock.co.uk/games/mingw_sse/) is, but there are some hints you could try.

**Comment by heckflosse** [comment]
@Floessie Yes, that's a known problem. For this reason RT win32 builds are made with -mstackrealign. For win64 builds this was not necessary in past and should still not be necessary.
Also, the sse4 code works fine here. It's just the non sse4 code which crashes win64 release builds.

**Comment by heckflosse** [comment]
@Floessie I found a solution for SSE2 (non SSE4) code which does not need MMX registers and does not crash. Here's some test code which can easily adopted to getClutValues():
```
    uint16_t dummy[8] = {1,2,3,4};
    __m128i v_values = _mm_loadu_si128(reinterpret_cast<const __m128i*>(dummy));

    vint testi = _mm_shuffle_epi32(v_values, _MM_SHUFFLE(1,0,1,0));
    vint testi2 = _mm_shufflelo_epi16( testi, _MM_SHUFFLE(1,1,0,0));
    testi2 = _mm_shufflehi_epi16( testi2, _MM_SHUFFLE(3,3,2,2));
    testi2 = vandm(testi2,_mm_set1_epi32(0x0000ffff));
    vfloat test = _mm_cvtepi32_ps(testi2);

    float test2[4];
    _mm_storeu_ps(test2,test);
    printf("%f %f %f %f\n",test2[0],test2[1],test2[2],test2[3]);

```

**Comment by heckflosse** [comment]
@Floessie [Here](https://gist.github.com/heckflosse/270449aca8a7634339ce5386e476ebd7) is a patch for your dedusting branch.

**Comment by Floessie** [comment]
@heckflosse YEAH!!! Breakthrough! :+1:  Not only this shall work (still cannot test, as I'm not on Windows), but it's nearly as fast as the SSE4 version (I was a bit skeptical at first due to the sheer number of instructions):
- 233ms for SSE4
- 243ms for SSE2
- 275ms with `_mm_set_ps()` implemented for comparison

It's committed on my dedusting branch for you to retest.

Great work! Thanks a lot!

**Comment by heckflosse** [comment]
@Floessie Retested! Works fine. Feel free to change the var names and so on to your coding style and make a PR. Maybe astyle it too. Don't remember if I did that.

**Comment by heckflosse** [comment]
@Floessie _mm_set1_epi32(0x0000ffff) could be called once instead of twice in my code. But maybe compiler optimizes it away...

**Comment by heckflosse** [comment]
@Floessie 
> (I was a bit skeptical at first due to the sheer number of instructions)

The number of instructions are:
1. SSE4 version : 6 per getClutValues() call
2. SSE2 version: 12 per getClutValues() call
3. MMX  version: 16 per getClutValues() call

if I counted correctly

**Comment by Floessie** [comment]
@heckflosse Yes, it's clear to me that a line count doesn't translate to the number of instructions, that's why I wrote "at first". :) I'll make the mask a constant and file the PR this evening. Again, thanks for solving that crash. Still, there is no explanation as to why the MMX instructions miscompile in this case, or have you found an answer?

**Comment by heckflosse** [comment]
@Floessie I searched a bit for information on Windows 64 bit and MMX but found nothing reliable. Anyway, it's solved now. That's the important thing.

**Comment by Floessie** [comment]
@heckflosse Definitely! I'm very glad, you found such a perfect solution. And [here](https://github.com/Beep6581/RawTherapee/pull/3282) is my PR.

**Comment by heckflosse** [comment]
@Floessie My I suggest a tiny change?
In the current implementation the +8 at buffer allocation can be reduced to +4 and the comment in that line is also not true anymore as we use the unaligned 16 bytes load now for non SSE4 code too ;-)
