### ISSUE TITLE
GTK3 GUI oddities - empty spaces

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#3261]
I noticed in the last weeks that empty spaces appear in some conditions. For example open any photo, go to the Wavelet tab and right-click on Edge Sharpness. The whole Wavelet Levels tool moves down and there is a large gap above it.
Reproducible 100%.

The same happens if I manually left-click on each sub-tool to hide it, instead of right-clicking on Edge Sharpness.

![scrot_2016-04-21 090241](https://cloud.githubusercontent.com/assets/5844619/14700432/d9b8cbc2-079f-11e6-83b1-9476263415b8.png)

@Hombre57 do you know where to look?

**Comment by Hombre57** [comment]
Is it specific to the Wavelet tab ?

**Comment by Beep6581** [comment]
I could not reproduce it now in any other tab so I must answer "yes", but it happened to me a few days ago from the File Browser tab in some non-Wavelet tab. Maybe it happens in other tabs too when the combination of collapsed and expanded sub-tools is right - I tried now just by right-clicking on each tool and sub-tool and could not reproduce it elsewhere, but can reproduce it 100% in Wavelet - Edge Sharpness.

**Comment by sguyader** [comment]
It looks like this happens with the HSV equalizer too.

**Comment by Hombre57** [comment]
Is it specific to the RawTherapee theme or Toowaboo's theme as well ? With the later and Gtk3.20, I cannot reproduce. Unfortunately, Gtk3.20 is broken and I don't know how to come back to 3.18 or 3.16, so I'm a bit stuck at the moment. :(

**Comment by Beep6581** [comment]
I'm on 3.18.7 using the official RT theme.

I confirm @sguyader's issue as well. I didn't notice it because when the curves are set to linear it doesn't happen. When you set either of them to Equalizer then it happens.

So there is the culprit! Curves. I tried it now and can reproduce it using the following when the curve is not linear:
* L*a*b* Adjustments
* Defringe
* Vibrance
* Black-and-White
* HSV
* RGB
* Wavelet Levels - Toning, Edge Sharpness, Gamut, Final Touchup

Can't reproduce in:
* Exposure
* Retinex
* CIECAM02
* Noise Reduction
* Color Toning
* Wavelet Levels - Residual Image HH

**Comment by TooWaBoo** [comment]
Looks like it's fixed in RT 4.2.942.

**Comment by Beep6581** [comment]
Unfortunately it's not fixed. It's not related to any specific theme. Looks like the vertical space requested when a curve widget is expanded is misbehaving.

**Comment by Beep6581** [comment]
The `gtk3-bugfix` branch still shows this gap problem:
https://i.imgur.com/DLyr8ev.jpg
But!
I think there is a new behavior, as it's unlikely I haven't noticed it before. Maybe it helps track down the problem. Here's what happens:

1. Right-click on any tool.
2. Right-click on L*a*b* Adjustments. Sometimes the gap problem triggers, but usually not. https://i.imgur.com/qcoAtkQ.jpg
3. Click on the L\* curve to close it.
4. Click on it again to expand it. Now the gap bug triggers. Reproducible: always. https://i.imgur.com/Uw8BMKO.jpg
5. When I move the mouse cursor over the L\* combobox, the rest of that panel appears under the CIE Color Appearance Model 2002 tool. http://i.imgur.com/TYGEcwL.jpg
6. The moment the cursor moves off of the L\* tool (any direction) everything fixes itself. https://i.imgur.com/pnOQ66h.jpg
7. Instead of step 5, I could have moved it over any other combobox. If I did that, skip step 5 and go to step 6. It has to be a combobox in the toolpanel, nothing else triggers the "fix".

**Comment by Hombre57** [comment]
Is the bug still there with latest commits ?

**Comment by Beep6581** [comment]
Yes, it is still there in commit 6438645b2142488347dc82b2f1bd46123aa5ff9a
https://i.imgur.com/caLXhp3.jpg
