### ISSUE TITLE
Incorrect histogram is shown if image was manipulated after histogram was hidden

### ISSUE THREAD

**Issue by aserebryakov** [Beep6581/RawTherapee#3297]
**Scenario:**

1. Open image in editor
1. Hide left panel
1. Change contrast to 100
1. Show left panel

**Expected:**
Histogram corresponds the image

**Actual:**
Histogram is not updated

**Build:** 4.2.854
**OS:** Ubuntu 16.04

**Comment by Beep6581** [comment]
Confirmed in `gtk3`, haven't tried `master`.

**Comment by heckflosse** [comment]
Confirmed in master

**Comment by maxiking01** [comment]
Hi, Dawid Król from RawTherapee's forum,
I can confirm that problem still persist on gtk3 branch. I will take this issue and see what I can do about it.

**Comment by Beep6581** [comment]
Yay!

**Comment by maxiking01** [comment]
![wrong histogram](https://cloud.githubusercontent.com/assets/17032029/16813483/f39069be-4931-11e6-96ae-4543744f1d30.jpg)
I noticed that histogram is incorrectly drawn because there are multiple curves for one color. I don't think that is correct. It also happens on the other raw files too.

**Comment by Beep6581** [comment]
@maxiking01 there is a single histogram curve per color. The reason your curves and whole UI look wrong is because your RawTherapee is not using the theme file. Get the latest build from our website (I just uploaded a new build), go to Preferences and set the theme to "RawTherapee". Also note that RawTherapee does not support Gtk+ 3.20 yet, only 3.18.* and below.

RawTherapee should look like this:
![imgur-2016_07_13-20 02 33](https://cloud.githubusercontent.com/assets/5844619/16814149/d3309754-4934-11e6-8751-54d6893b1eec.png)

**Comment by leeoniya** [comment]
@Beep6581 is 4.2.1148 built from master (so can be considered RT5-pre?)

**Comment by Beep6581** [comment]
No, it's built from the `gtk3` branch. The idea is to stop committing to `master` and switch to `gtk3` soon.
Apart from the user interface, `master`==`gtk3`. Both can be considered RT5-alpha.

**Comment by leeoniya** [comment]
k thx, i'm mostly interested in the recent large perf boosts. my laptop's thermal management will be happy :)

**Comment by Hombre57** [comment]
Histogram wrong refresh should be solved in the gtk3-bugfix branch.

**Comment by maxiking01** [comment]
It still does not refresh histogram after showing the left panel. However your patch solved another problem which occurred also with this bug. When you reproduced steps described in scenario and then changed contrast of the histogram the one with previous value of contrast and with new one were drawn on the same area. @Hombre57 are you going to solve this bug? If you do I'll change to other task because two people doesn't have to work on it.

**Comment by Beep6581** [comment]
@maxiking01 you wrote on July 13, three months ago, "I will take this issue and see what I can do about it".

**Comment by Hombre57** [comment]
Yes, I'm investigating.

**Comment by Hombre57** [comment]
Can I solve this in gtk3 only ? I think it's a minor issue and it's way simpler to solve in Gtk3 than master (i.e. Gtk2).

**Comment by heckflosse** [comment]
@Hombre57 `Can I solve this in gtk3 only ?` Yes.

**Comment by Hombre57** [comment]
Solved in gtk3 branch, what will soon be the new master.

**Comment by maxiking01** [comment]
@Beep6581 I tried to solved it with the help of gtk documentation but I stuck on the unknown territory of ui framework . I should've asked somebody for help in this time. I asked because I didn't to double the effort.
