### ISSUE TITLE
Control point values change when switching between CPs in locallab

### ISSUE THREAD

**Issue by dngimage** [Beep6581/RawTherapee#3530]
version 4.2.1249 Win64
If you add several control points and set blur radius to a value of let's say 20 for each, then switch between control points, the blur radius will change to 100 on its own.

**Comment by Beep6581** [comment]
@dngimage it would be more helpful if you included the changeset hash instead of the version.

**Comment by Desmis** [comment]
I think now the bug is fixed.

You must clean cache and delete *.mip files

:)

**Comment by dngimage** [comment]
Thanks for the reply guys.

Deleted the cache, profile and *.mip and still have the bug.

Using:

Branch: locallab
Version: 4.2.1249
Changeset: a6c62076098b68e9a98650b894d11dafa232deb7
Compiler: gcc 6.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V2.24.4
Build type: release
Build flags:  -m64 -mwin32 -mthreads -std=gnu++11 -Werror=unused-label -Werror=unknown-pragmas -Wno-aggressive-loop-optimizations -std=gnu++11 -mtune=generic -Werror=unused-label -fopenmp -Werror=unknown-pragmas -mwindows -DNDEBUG -msse2 -mfpmath=sse -O3
Link flags: -m64 -mthreads  -static-libgcc   -mtune=generic -mwindows -s -O3
OpenMP support: ON
MMAP support: ON

**Comment by heckflosse** [comment]
@dngimage As @Desmis has pushed a fix you should also pull 'locallab' again from git ;)

**Comment by dngimage** [comment]
Thanks for the fix guys :)

**Comment by Desmis** [comment]
@heckflosse 

Ingo
Thank you, for this information :)
