### ISSUE TITLE
Fix issues detected by AddressSanitizer

### ISSUE THREAD

**Issue by heckflosse** [Beep6581/RawTherapee#3913]
I created a new branch to fix issues detected by AddressSanitizer : https://github.com/Beep6581/RawTherapee/tree/san_address

**Comment by agriggio** [comment]
@heckflosse Ingo, can I push to this branch? I have fixed some of the memory leaks reported by LeakSanitizer (although I'm not sure that they are enough to solve #3908 )

**Comment by heckflosse** [comment]
@agriggio Alberto, of course you can

**Comment by heckflosse** [comment]
@agriggio Alberto, thanks for the fixes. Unfortunately #3908 is not solved :(

**Comment by heckflosse** [comment]
@agriggio Alberto, I fixed some more memory leaks.
The current output of the AddressSanitizer is much cleaner now and lets us detect further leaks much easier:

```
ingo@ingo-VirtualBox ~/repo-rt/build $ debug/rawtherapee

=================================================================
==11968==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16384 byte(s) in 1 object(s) allocated from:
    #0 0x7fdfb6eba602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7fdfb58d1718 in g_malloc (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4f718)

Direct leak of 2560 byte(s) in 4 object(s) allocated from:
    #0 0x7fdfb6eba961 in realloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98961)
    #1 0x7fdfaf2b700a  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d00a)

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x7fdfb6eba602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7fdfaf2b70b9  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d0b9)

Indirect leak of 7296 byte(s) in 228 object(s) allocated from:
    #0 0x7fdfb6eba602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7fdfaf2a5e8f  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0xbe8f)

Indirect leak of 3065 byte(s) in 266 object(s) allocated from:
    #0 0x7fdfb6eba602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7fdfb1c248d9 in __strdup (/lib/x86_64-linux-gnu/libc.so.6+0x8a8d9)

Indirect leak of 2336 byte(s) in 73 object(s) allocated from:
    #0 0x7fdfb6eba79a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7fdfaf2b77c8  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d7c8)

Indirect leak of 1408 byte(s) in 44 object(s) allocated from:
    #0 0x7fdfb6eba79a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7fdfaf2b6c9c  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1cc9c)

Indirect leak of 384 byte(s) in 12 object(s) allocated from:
    #0 0x7fdfb6eba79a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7fdfaf2b6b26  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1cb26)

Indirect leak of 96 byte(s) in 2 object(s) allocated from:
    #0 0x7fdfb6eba602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7fdfaf2b142d in FcLangSetCreate (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1742d)

SUMMARY: AddressSanitizer: 33785 byte(s) leaked in 631 allocation(s).
```

**Comment by heckflosse** [comment]
@agriggio Alberto, I found another leak. But I don't get how to fix it.

To reproduce

1. Create a folder with 2 images
2. Apply neutral profile to both images
3. Close rt
4. Start rt
5. Select second image in file browser (don't open it)
6. go to batch edit
7. change a setting (e.g. change saturation from 0 to 1)
8. close rt

This gives the following leak report:

```
=================================================================
==14478==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 5120 byte(s) in 8 object(s) allocated from:
    #0 0x7f8799be2961 in realloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98961)
    #1 0x7f8791fdf00a  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d00a)

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x7f8799be2602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f8791fdf0b9  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d0b9)

Direct leak of 144 byte(s) in 1 object(s) allocated from:
    #0 0x7f8799be3532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0xaa50ef in FileBrowserEntry::updateImage(rtengine::IImage8*, double, rtengine::procparams::CropParams) /home/ingo/repo-rt/rtgui/filebrowserentry.cc:208
    #2 0xedb509 in ThumbImageUpdater::Impl::processNextJob() /home/ingo/repo-rt/rtgui/thumbimageupdater.cc:160
    #3 0xedd1b8 in sigc::bound_mem_functor0<void, ThumbImageUpdater::Impl>::operator()() const /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:1787
    #4 0xedd015 in sigc::adaptor_functor<sigc::bound_mem_functor0<void, ThumbImageUpdater::Impl> >::operator()() const /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:256
    #5 0xedcb16 in sigc::internal::slot_call0<sigc::bound_mem_functor0<void, ThumbImageUpdater::Impl>, void>::call_it(sigc::internal::slot_rep*) /usr/include/sigc++-2.0/sigc++/functors/slot.h:108
    #6 0x7f879799b5c1  (/usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1+0x595c1)

Indirect leak of 68464 byte(s) in 1 object(s) allocated from:
    #0 0x7f8799be2602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x10af1ef in AlignedBuffer<unsigned char>::resize(unsigned long, int) /home/ingo/repo-rt/rtengine/alignedbuffer.h:110
    #2 0x10ae0d6 in rtengine::ChunkyRGBData<unsigned char>::allocate(int, int) /home/ingo/repo-rt/rtengine/iimage.h:1312
    #3 0x10a8434 in rtengine::Image8::Image8(int, int) /home/ingo/repo-rt/rtengine/image8.cc:33
    #4 0x1408c87 in rtengine::Thumbnail::processImage(rtengine::procparams::ProcParams const&, int, rtengine::TypeInterpolation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, double, float, float, float, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double&) /home/ingo/repo-rt/rtengine/rtthumbnail.cc:1307
    #5 0xee374e in Thumbnail::processThumbImage(rtengine::procparams::ProcParams const&, int, double&) /home/ingo/repo-rt/rtgui/thumbnail.cc:604
    #6 0xedb444 in ThumbImageUpdater::Impl::processNextJob() /home/ingo/repo-rt/rtgui/thumbimageupdater.cc:155
    #7 0xedd1b8 in sigc::bound_mem_functor0<void, ThumbImageUpdater::Impl>::operator()() const /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:1787
    #8 0xedd015 in sigc::adaptor_functor<sigc::bound_mem_functor0<void, ThumbImageUpdater::Impl> >::operator()() const /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:256
    #9 0xedcb16 in sigc::internal::slot_call0<sigc::bound_mem_functor0<void, ThumbImageUpdater::Impl>, void>::call_it(sigc::internal::slot_rep*) /usr/include/sigc++-2.0/sigc++/functors/slot.h:108
    #10 0x7f879799b5c1  (/usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1+0x595c1)

Indirect leak of 14592 byte(s) in 456 object(s) allocated from:
    #0 0x7f8799be2602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f8791fcde8f  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0xbe8f)

Indirect leak of 6231 byte(s) in 534 object(s) allocated from:
    #0 0x7f8799be2602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f879494c8d9 in __strdup (/lib/x86_64-linux-gnu/libc.so.6+0x8a8d9)

Indirect leak of 4640 byte(s) in 145 object(s) allocated from:
    #0 0x7f8799be279a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7f8791fdf7c8  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d7c8)

Indirect leak of 2816 byte(s) in 88 object(s) allocated from:
    #0 0x7f8799be279a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7f8791fdec9c  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1cc9c)

Indirect leak of 768 byte(s) in 24 object(s) allocated from:
    #0 0x7f8799be279a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7f8791fdeb26  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1cb26)

Indirect leak of 280 byte(s) in 1 object(s) allocated from:
    #0 0x7f8799be3532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0x1408c6e in rtengine::Thumbnail::processImage(rtengine::procparams::ProcParams const&, int, rtengine::TypeInterpolation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, double, float, float, float, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double&) /home/ingo/repo-rt/rtengine/rtthumbnail.cc:1307
    #2 0xee374e in Thumbnail::processThumbImage(rtengine::procparams::ProcParams const&, int, double&) /home/ingo/repo-rt/rtgui/thumbnail.cc:604
    #3 0xedb444 in ThumbImageUpdater::Impl::processNextJob() /home/ingo/repo-rt/rtgui/thumbimageupdater.cc:155
    #4 0xedd1b8 in sigc::bound_mem_functor0<void, ThumbImageUpdater::Impl>::operator()() const /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:1787
    #5 0xedd015 in sigc::adaptor_functor<sigc::bound_mem_functor0<void, ThumbImageUpdater::Impl> >::operator()() const /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:256
    #6 0xedcb16 in sigc::internal::slot_call0<sigc::bound_mem_functor0<void, ThumbImageUpdater::Impl>, void>::call_it(sigc::internal::slot_rep*) /usr/include/sigc++-2.0/sigc++/functors/slot.h:108
    #7 0x7f879799b5c1  (/usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1+0x595c1)

Indirect leak of 192 byte(s) in 4 object(s) allocated from:
    #0 0x7f8799be2602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f8791fd942d in FcLangSetCreate (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1742d)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7f8799be2602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f879863828f  (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x8e28f)
    #2 0x10ad06f in rtengine::ImageIO::ImageIO() /home/ingo/repo-rt/rtengine/imageio.h:107
    #3 0x10a834e in rtengine::Image8::Image8(int, int) /home/ingo/repo-rt/rtengine/image8.cc:31
    #4 0x1408c87 in rtengine::Thumbnail::processImage(rtengine::procparams::ProcParams const&, int, rtengine::TypeInterpolation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, double, float, float, float, float, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double&) /home/ingo/repo-rt/rtengine/rtthumbnail.cc:1307
    #5 0xee374e in Thumbnail::processThumbImage(rtengine::procparams::ProcParams const&, int, double&) /home/ingo/repo-rt/rtgui/thumbnail.cc:604
    #6 0xedb444 in ThumbImageUpdater::Impl::processNextJob() /home/ingo/repo-rt/rtgui/thumbimageupdater.cc:155
    #7 0xedd1b8 in sigc::bound_mem_functor0<void, ThumbImageUpdater::Impl>::operator()() const /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:1787
    #8 0xedd015 in sigc::adaptor_functor<sigc::bound_mem_functor0<void, ThumbImageUpdater::Impl> >::operator()() const /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:256
    #9 0xedcb16 in sigc::internal::slot_call0<sigc::bound_mem_functor0<void, ThumbImageUpdater::Impl>, void>::call_it(sigc::internal::slot_rep*) /usr/include/sigc++-2.0/sigc++/functors/slot.h:108
    #10 0x7f879799b5c1  (/usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1+0x595c1)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f8799be3532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0xaa330c in FileBrowserEntry::FileBrowserEntry(Thumbnail*, Glib::ustring const&) /home/ingo/repo-rt/rtgui/filebrowserentry.cc:45
    #2 0xdca10a in PreviewLoader::Impl::processNextJob() /home/ingo/repo-rt/rtgui/previewloader.cc:134
    #3 0xdcc9e4 in sigc::bound_mem_functor0<void, PreviewLoader::Impl>::operator()() const /usr/include/sigc++-2.0/sigc++/functors/mem_fun.h:1787
    #4 0xdcc6e7 in sigc::adaptor_functor<sigc::bound_mem_functor0<void, PreviewLoader::Impl> >::operator()() const /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:256
    #5 0xdcc2a4 in sigc::internal::slot_call0<sigc::bound_mem_functor0<void, PreviewLoader::Impl>, void>::call_it(sigc::internal::slot_rep*) /usr/include/sigc++-2.0/sigc++/functors/slot.h:108
    #6 0x7f879799b5c1  (/usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1+0x595c1)

SUMMARY: AddressSanitizer: 103559 byte(s) leaked in 1265 allocation(s).
```

Doing the same on first instead of second image gives this report:

```
=================================================================
==14544==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 5120 byte(s) in 8 object(s) allocated from:
    #0 0x7f653697a961 in realloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98961)
    #1 0x7f652ed7700a  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d00a)

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x7f653697a602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f652ed770b9  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d0b9)

Indirect leak of 14592 byte(s) in 456 object(s) allocated from:
    #0 0x7f653697a602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f652ed65e8f  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0xbe8f)

Indirect leak of 6231 byte(s) in 534 object(s) allocated from:
    #0 0x7f653697a602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f65316e48d9 in __strdup (/lib/x86_64-linux-gnu/libc.so.6+0x8a8d9)

Indirect leak of 4640 byte(s) in 145 object(s) allocated from:
    #0 0x7f653697a79a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7f652ed777c8  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d7c8)

Indirect leak of 2816 byte(s) in 88 object(s) allocated from:
    #0 0x7f653697a79a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7f652ed76c9c  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1cc9c)

Indirect leak of 768 byte(s) in 24 object(s) allocated from:
    #0 0x7f653697a79a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7f652ed76b26  (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1cb26)

Indirect leak of 192 byte(s) in 4 object(s) allocated from:
    #0 0x7f653697a602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f652ed7142d in FcLangSetCreate (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1742d)

SUMMARY: AddressSanitizer: 34615 byte(s) leaked in 1260 allocation(s).
```

**Comment by Thanatomanic** [comment]
There are probably more issues the sanitizer can detect. See e.g. #4185 and #4184.
Is it already a common practice to check a release candidate build for such things?
