### ISSUE TITLE
Where is console ?

### ISSUE THREAD

**Issue by Desmis** [Beep6581/RawTherapee#3982]
I merge with dev and now, in release mode, I cannot see console ?
And obviously no info "printf"...

There is probably in "Prefreences" or in "option" a check button or other thing ?

Thank you

**Comment by heckflosse** [comment]
@Desmis Jacques, does this happen in Release or Debug build?

**Comment by Desmis** [comment]
@heckflosse 

Ingo

I only test with "Release", and I test on 2 differents builds  from 2 differents clones.
a) newlocallab
b) dev

I have been very surprise... Am I alone with this probem.  I am with Windows8

**Newlocallab**
Version: 5.1-298-g2ff1ea45
Branch: newlocallab
Commit: 2ff1ea45
Commit date: 2017-07-24
Compiler: gcc 6.3.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

**Dev**
Version: 5.1-182-g732ac607
Branch: dev
Commit: 732ac607
Commit date: 2017-07-23
Compiler: gcc 6.3.0
Processor: undefined
System: Windows
Bit depth: 64 bits
Gtkmm: V3.22.0
Build type: release
Build flags:  -std=c++11 -march=native -Werror=unused-label -fopenmp -Werror=unknown-pragmas -Wall -Wno-unused-result -Wno-deprecated-declarations -O3 -DNDEBUG
Link flags:  -march=native
OpenMP support: ON
MMAP support: ON

**Comment by Beep6581** [comment]
@Desmis you must now start RawTherapee from a console - a console won't open automatically for release builds. See commit bc3d82a17a2f03c9b5ff007570a6c08b60666573

**Comment by Desmis** [comment]
@heckflosse 

Ok, 

If I run RT in a console with ==> Rawtherapee /w, I have information un console...It is not intuitive :)

jacques

**Comment by heckflosse** [comment]
@Desmis

Jacques, maybe it's caused by this commit cb130ae . I will take a look.

Ingo

**Comment by heckflosse** [comment]
@Desmis

Jacques, this patch should fix the issue
```patch
diff --git a/rtgui/main.cc b/rtgui/main.cc
index 099751f0..cba4a767 100644
--- a/rtgui/main.cc
+++ b/rtgui/main.cc
@@ -481,7 +481,7 @@ int main(int argc, char **argv)
     // suppression of annoying error boxes
     SetErrorMode(SEM_FAILCRITICALERRORS | SEM_NOGPFAULTERRORBOX | SEM_NOOPENFILEERRORBOX);
 
-    if(argc > 1) {
+    if(argc > 1 || options.rtSettings.verbose) {
         int ret = processLineParams( argc, argv);
         if (options.rtSettings.verbose || (!remote && !Glib::file_test (argv1, Glib::FILE_TEST_EXISTS ) && !Glib::file_test (argv1, Glib::FILE_TEST_IS_DIR))) {
             bool stdoutRedirectedtoFile = (GetFileType(GetStdHandle(STD_OUTPUT_HANDLE)) == 0x0001);

```

**Comment by Desmis** [comment]
@heckflosse 

I tested by replacing -    if(argc > 1) {
by==>    if(argc > 1 || options.rtSettings.verbose) {

Compile fine, but does not solved the problem. 
But no worry, I'll run RT with console and "Rawtherapee w"

jacques

**Comment by Beep6581** [comment]
Status?

**Comment by Desmis** [comment]
I think we can close.
Now when I want to display information in console ==> ./rawtherapee w

Jacques
