### ISSUE TITLE
Segfault in gaussianBlur (USM)

### ISSUE THREAD

**Issue by Beep6581** [Beep6581/RawTherapee#4528]
`5.4-258-g`5d27eea8
https://filebin.net/sitr9sambhk8znk2
Add the raw file via dedicated fast export to the queue, start the queue, and eventually it crashes:
```text
Thread 39 "rawtherapee" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 15923]
0x00007ffff0e34c6f in ?? () from /lib64/libc.so.6
(gdb)
(gdb) bt full
#0  0x00007ffff0e34c6f in ?? () from /lib64/libc.so.6
No symbol table info available.
#1  0x000055555644527f in (anonymous namespace)::gaussianBlurImpl<float> (src=0x7fffb814b720, dst=0x7fffb81107e0, W=1161, H=773, sigma=0.10618131756782533, buffer=0x0, gausstype=GAUSS_STANDARD, buffer2=0x0) at /home/morgan/programs/code-rawtherapee/rtengine/gauss.cc:1193
        GAUSS_SKIP = 0.25
        GAUSS_3X3_LIMIT = 0.59999999999999998
        GAUSS_DOUBLE = 70
#2  0x0000555556444d53 in gaussianBlur (src=0x7fffb814b720, dst=0x7fffb81107e0, W=1161, H=773, sigma=0.10618131756782533, buffer=0x0, gausstype=GAUSS_STANDARD, buffer2=0x0) at /home/morgan/programs/code-rawtherapee/rtengine/gauss.cc:1299
No locals.
#3  0x000055555611ba87 in rtengine::ImProcFunctions::sharpening () at /home/morgan/programs/code-rawtherapee/rtengine/ipsharpen.cc:195
        lab = 0x7fffb8020250
        b2 = 0x7fffb81107e0
        sharpenParam = @0x55555dcbf918: {enabled = true, radius = 0.10618131756782533, amount = 200, threshold = {bottom_left = 20, top_left = 80, bottom_right = 2000, top_right = 1200, init_eql = false, is_double = true}, edgesonly = false, edges_radius = 1.8999999999999999, edges_tolerance = 1800, halocontrol = false, halocontrol_amount = 85, method = {static npos = 18446744073709551615, string_ = "usm"}, deconvamount = 75, deconvradius = 0.14479270577430725, deconviter = 30, deconvdamping = 20}
        this = 0x7fffb80174d0
        W = 1161
        H = 773
        b3 = 0x0
#4  0x00007ffff14f8296 in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/libgomp.so.1
No symbol table info available.
#5  0x00007ffff10aea53 in ?? () from /lib64/libpthread.so.0
No symbol table info available.
#6  0x00007ffff0de62df in clone () from /lib64/libc.so.6
No symbol table info available.
```

**Comment by heckflosse** [comment]
This patch should fix the crash:

```diff
diff --git a/rtengine/simpleprocess.cc b/rtengine/simpleprocess.cc
index 6a59241e1..718192cfd 100644
--- a/rtengine/simpleprocess.cc
+++ b/rtengine/simpleprocess.cc
@@ -1211,17 +1211,15 @@ private:
                     }
 
                 float **buffer = new float*[ch];
+                float *data = new float[cw * ch];
 
                 for (int i = 0; i < ch; i++) {
-                    buffer[i] = new float[cw];
+                    buffer[i] = &data[i * cw];
                 }
 
                 ipf.sharpening (labView, (float**)buffer, params.prsharpening);
 
-                for (int i = 0; i < ch; i++) {
-                    delete [] buffer[i];
-                }
-
+                delete [] data;
                 delete [] buffer;
             }
         }

```

**Comment by Beep6581** [comment]
@heckflosse unfortunately it still crashes. New backtrace coming soon.

**Comment by Beep6581** [comment]
```text
Thread 38 "rawtherapee" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 31998]
0x00007ffff0e34c6f in ?? () from /lib64/libc.so.6
(gdb) bt full
#0  0x00007ffff0e34c6f in ?? () from /lib64/libc.so.6
No symbol table info available.
#1  0x0000555556444f39 in (anonymous namespace)::gaussianBlurImpl<float> (src=0x7fffb4136820, dst=0x7fffb4134fe0, W=1161, H=773, sigma=0.10618131756782533, buffer=0x0, gausstype=GAUSS_STANDARD, buffer2=0x0) at /home/morgan/programs/code-rawtherapee/rtengine/gauss.cc:1193
        GAUSS_SKIP = 0.25
        GAUSS_3X3_LIMIT = 0.59999999999999998
        GAUSS_DOUBLE = 70
#2  0x0000555556444a0d in gaussianBlur (src=0x7fffb4136820, dst=0x7fffb4134fe0, W=1161, H=773, sigma=0.10618131756782533, buffer=0x0, gausstype=GAUSS_STANDARD, buffer2=0x0) at /home/morgan/programs/code-rawtherapee/rtengine/gauss.cc:1299
No locals.
#3  0x000055555611b761 in rtengine::ImProcFunctions::sharpening () at /home/morgan/programs/code-rawtherapee/rtengine/ipsharpen.cc:195
        lab = 0x7fffb4017f70
        b2 = 0x7fffb4134fe0
        sharpenParam = @0x55555ddc4538: {enabled = true, radius = 0.10618131756782533, amount = 200, threshold = {bottom_left = 20, top_left = 80, bottom_right = 2000, top_right = 1200, init_eql = false, is_double = true}, edgesonly = false, edges_radius = 1.8999999999999999, edges_tolerance = 1800, halocontrol = false, halocontrol_amount = 85, method = {static npos = 18446744073709551615, string_ = "usm"}, deconvamount = 75, deconvradius = 0.14479270577430725, deconviter = 30, deconvdamping = 20}
        this = 0x7fffb4014000
        W = 1161
        H = 773
        b3 = 0x0
#4  0x00007ffff14f8296 in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/libgomp.so.1
No symbol table info available.
#5  0x00007ffff10aea53 in ?? () from /lib64/libpthread.so.0
No symbol table info available.
#6  0x00007ffff0de62df in clone () from /lib64/libc.so.6
No symbol table info available.
```

**Comment by heckflosse** [comment]
@Beep6581 please try this patch instead of the last one

```diff
diff --git a/rtengine/gauss.cc b/rtengine/gauss.cc
index 972021336..6f7b0164c 100644
--- a/rtengine/gauss.cc
+++ b/rtengine/gauss.cc
@@ -1190,7 +1190,11 @@ template<class T> void gaussianBlurImpl(T** src, T** dst, const int W, const int
         if (sigma < GAUSS_SKIP) {
             // don't perform filtering
             if (src != dst) {
-                memcpy (dst[0], src[0], W * H * sizeof(T));
+                for(int i = 0; i < H; ++i) {
+                    for(int j = 0; j < W; ++j) {
+                        dst[i][j] = src[i][j];
+                    }
+                }
             }
         } else if (sigma < GAUSS_3X3_LIMIT) {
             if(src != dst) {

```

**Comment by Beep6581** [comment]
That fixed it @heckflosse
