### ISSUE TITLE
Tilting always scrolls to the left

### ISSUE THREAD

**Issue by Nindaleth** [Beep6581/RawTherapee#4728]
RT 5.4 on Linux Fedora 28 (installed from default repo). In Editor tab, scrolling the top panel is inconsistent and at one point also buggy. I have a 4-way mousewheel, so I can scroll both vertically and horizontally (tilt).

When scrolling over the thumbnails:
- scrolling down moves to the right, scrolling up moves to the left
- tilting always moves to the left, regardless of the tilting direction - that's buggy

When scrolling over the horizontal scrollbar:
- scrolling down moves to the left, scrolling up moves to the right - that's inconsistent - it's the opposite direction from what the thumbnails scrolling does
- tilting works as expected - left=left, right=right
- scrolling over the scrollbar goes much faster than scrolling over the thumbnails (might be by design)

**Comment by Beep6581** [comment]
This issue was already addressed, though I don't remember which version it's in. Please test the latest dev build and report whether it's reproducible. 
https://discuss.pixls.us/t/download-rawtherapee-development-builds/2924

**Comment by Nindaleth** [comment]
Tested with 5.4-662-gf70cdd01, still reproducible. I noticed the following changes:

- scrolling over the thumbnails and over the horizontal scrollbar is now more similar in speed (thumbnails now move faster, but now the difference is not as big on my 1680x1050 screen)
- tilting over the thumbnails does not work at all

Thumbnails will still go the opposite way than the scrollbar will go when scrolled over.

BTW, the linked nightly builds (at least for Linux) are quite old, AppImage of the dev branch lists 5.4-524 as the latest available build.

**Comment by Thanatomanic** [comment]
@Nindaleth The horizontal scrolling seems to be an upstream issue with GTK https://gitlab.gnome.org/GNOME/gtk/issues/1065

**Comment by Beep6581** [comment]
> scrolling down moves to the left, scrolling up moves to the right - that's inconsistent - it's the opposite direction from what the thumbnails scrolling does

Our code seems fine:
https://github.com/Beep6581/RawTherapee/blob/dev/rtgui/thumbbrowserbase.cc#L78

> tilting always moves to the left, regardless of the tilting direction - that's buggy

Only up and down directions are handled. @Nindaleth are you able to test patches?

**Comment by Nindaleth** [comment]
@Thanatomanic Oh, OK, that explains how not that many people mind. Thanks for the info

@Beep6581 Sure, if you have patches I'll gladly try them :-)

**Comment by Beep6581** [comment]
So the only issue that could be addressed here is that scrolling sideways using a 4-way scrollwheel ("tilting"?) always scrolls to the left.

**Comment by Nindaleth** [comment]
The issue can also be reproduced when two-finger horizontal scrolling on a touchpad (I guess internally OS generates the same mouse events).

**Comment by Lawrence37** [comment]
Horizontal scrolling on my touchpad works as expected. If this is really the GTK issue (which has since been closed), then I think this issue can be closed.
