### ISSUE TITLE
LocalLab: Crash when Right<9 or Bottom<12 and Sharpening:ON

### ISSUE THREAD

**Issue by arturoisilvia** [Beep6581/RawTherapee#5583]
Hi,
I was going to do a red-eye reduction and wanted to give it some sharpness.
It has crashed me when exporting the image for having activated the Sharpening module of the Local tab and Right value <9 or Bottom value <12

It only crashes in RawTherapee_newlocallab-win64-5.7-1694-ge1a938e3a_WinVista_64 version
In these previous versions it works fine (there is no crash):
RawTherapee_newlocallab-win64-5.7-1670-g08e2ba79d_WinVista_64
RawTherapee_newlocallab-win64-5.7-1605-gcf226473c_WinVista_64

I attach the pp3 that can be loaded with any image. When you try to export to TIF or JPG with the sharpening module of the 'Local' tab, it will crash.

Process:
Complexity Local Adjustment: Expert
1 Open a image
2 Local-> Local Adjustment-> ON
3 Add a circle
4 Sharpening-> ON (Crash red_eyes_02.jpg)
5 Settings: Shape method: Symmetrical (mouse + sliders)
   Values ​​of:
	(Right - Bottom) (Crash red_eyes_01.jpg)
	(12 - 12)         either when exporting jpg or tif
	(11 - 12)         either when exporting jpg or tif
	(10 - 12)        either when exporting jpg or tif
	(9 - 12)        either when exporting jpg or tif
	(9 - 11)        crash when exporting jpg or tif
	(8 - 12)        crash when exporting jpg or tif

Rigth less than 9 or Bottom less than 12: Crash when exporting with sharpening ON.

attached files: 
[Error red eyes with Sharpening.zip](https://github.com/Beep6581/RawTherapee/files/4002904/Error.red.eyes.with.Sharpening.zip)
-----------------------------------------------------
Version: 5.7-1694-ge1a938e3a
Branch: newlocallab
Commit: e1a938e3a
Commit date: 2019-12-22
Compiler: x86_64-w64-mingw32-gcc\ 8.2.0
Processor: generic x86
System: Windows
Bit depth: 64 bits
Gtkmm: V3.24.2
Lensfun: V0.3.2.0
Build type: Release
Build flags: -mwin32\ -m64\ -mthreads\ -msse2\ -std=c++11\ -mtune=generic\ -Werror=unused-label\ -Werror=delete-incomplete\ -Wall\ -Wuninitialized\ -Wcast-qual\ -Wno-deprecated-declarations\ -Wno-unused-result\ -fopenmp\ -Werror=unknown-pragmas\ -Wno-aggressive-loop-optimizations\ -DNDEBUG\ -O3\ -ftree-vectorize
Link flags: -m64\ -mthreads\ -static-libgcc\ -mtune=generic\ -s\ -O3
OpenMP support: ON
MMAP support: ON

**Comment by Desmis** [comment]
@arturoisilvia 

Hello
Thank you for testing :)

I was not at home, but with my family in Paris

I think (I hope) the crash is fixed, with this commit 9422a0b

Thank you

Jacques

**Comment by arturoisilvia** [comment]
Calme, which by these dates has preference over all the family and nougat ;-)

Thanks for fixing it. I will try it.

Greetings
	Arturo

**Comment by arturoisilvia** [comment]
I reopen the issue because it still fails me in commit 9422a0b

1) In pp3 that I sent before you had to put a lower value to Right or Bottom
2) Have the Sharpening module-> ON 
3) Export (processing queue) to jpeg or TIFF

Attachment new pp3:
[Error red eyes with Sharpening-2.zip](https://github.com/Beep6581/RawTherapee/files/4006946/Error.red.eyes.with.Sharpening-2.zip)

Jacques, it's not urgent for me. Only the error still exists before releasing new stable version RT 5.8 or RT 6.0 with Local tab (that should be close to leaving).

Regards,
   Arturo.

**Comment by Desmis** [comment]
@arturoisilvia 

I will see again, but in my case, no crash....

jacques

**Comment by arturoisilvia** [comment]
No? Well, how strange ...
I have tried with another computer and with different files: dng, raf, cr2 ... and also crash.

Let's see, I put the process back to you:
Windows 10
RT 5.7-1699-g9422a0b7e (Compexity Local Adjustments: Expert)
Open any photo
Profile: Neutral
Load profile: Error red eyes with Sharpening-2.pp3
Put current image to processing queue (Shortcut: Ctrl-b)
Start processing:

![Crash red_eyes_03](https://user-images.githubusercontent.com/55624244/71543150-3164ff80-2970-11ea-90b3-cdfec07e5dfc.jpg)

No crash here?

**Comment by Desmis** [comment]
@arturoisilvia 

I know the process, but it depends of many factors, in some cases it works...even with small spot.

In fact, the problem is due to "builblendmask" use by "deconvsharpening", under 39 pixels for the size of the "windows" there is a crash, regardless of the positions...

It just post a fixed, when size of windows under H=39 or W=39 the program exit whitout threatment

Jacques

**Comment by arturoisilvia** [comment]
Well, I don't know what to say, but the version:

RawTherapee_newlocallab-win64-5.7-1670-g08e2ba79d_WinVista_64.exe

It works well: it doesn't fail me at any time. ¿?
Something must have changed.

**Comment by Desmis** [comment]
@arturoisilvia 

I have limited "sharp" (deconvolution) to a RT-spot minimum 39x39 pixels
I add a TOOLTIP for the expander, to explain sommary

Try to  "sharp" with wavelet, I found many bugs (mostly due to nonsense on my part), especially to set the maximum possible levels between : a) selection by the user, b) size of RT-spot, c) size of preview, and d) skip (I recommand to use 100% 1:1  - skip = 1)

Wavelet is in "Local contrast - wavelet"
The wavelet pyramid has been improved now you have:
0) selection range levels ex: 3 to 7 or 0 to 9, etc.
1) levels local contrast (in function luminance)
2) contrast and chroma on residual

Wavelet pyramid :
a) Clarity - sharp mask and general blend images (with all processes wavelet)
b) contrast by detail levels with sigma, offset, chroma and of course choice of levels contrast + or -
c) level dynamic range compression by levels (important ressources need), for example for "dramatic skies"
d)  blur levels - luma and chroma of course by level and residual image

jacques


jacques

**Comment by arturoisilvia** [comment]
Ok, I'll try wavelets. It will take me a little time to understand.
And as this sharp limitation is known, I conclude this conversation

Greetings.

**Comment by Desmis** [comment]
@arturoisilvia 
Yes there is a limitation to sharp (size), but you can still use sharp, to sharp very small area

You can use in "settings"
* transition value and **transition weakening**

Example
If the RT-spot is 50*50 sharp can be used
* set transition value to 10, you will have a "RT-spot" with plain effect for a 5x5 area
* if you set transition weakening to 1, of course, the speed of weakening is low, at 25x25 about 50% (0.5)
* but if you choose transition weakening to  10, at 25*25 it will be about 0.001, 0.5%

At 6x6 with transition weakening to 10 , the weakening is about 60%
at 8x8 with transition weakening to 10, the weakening is about 90%

**So by choosing a reduced transition (10% 15%)  and a strong weakening (9  10) you can use all the tools with better visibility and no risk of too small spot**  (Sharp, Wavelet, CBDL, etc.)

I change the default settings for transition
transition mini = 2 instead of 5
transition weakening maxi = 15, instead of 10

Jacques

**Comment by arturoisilvia** [comment]
I had already succeeded in replacing sharpening with pyramid wavelets with the local contrast levels curve and scope=100:
![Wavelets pyramid](https://user-images.githubusercontent.com/55624244/71556501-c122b080-2a39-11ea-9a72-4098bde8da53.jpg)

I have tried the sharpening module with spot size > at 39x39 and adjusting transitions value and weakening as you say and it has also worked well without errors. I had not fallen into these types of adjustments because when you make a red-eye reduction, you usually adjust the spot to the size of the iris of the eye. Thanks for the idea.

**Comment by Desmis** [comment]
The wavelet tool you have chosen works, but it is not the most suitable for what you want to do.

Try to use, "contrast by level" :)

When you say  "you usually adjust the spot to the size of the iris of the eye.", again, it works, but it's under using algorithms.
I wrote in the documentation that you had to do a cognitive unlearning... what you mention confirms it, as well as other remarks from users who want to make the spot coincide with the object to be treated !

jacques

**Comment by arturoisilvia** [comment]
Yes it's correct. I come from darktable .... and its " contrôles de type "lasso" ". So some memory remains for me ... ;-)

Greetings,
       Arturo
