### ISSUE TITLE
LibRaw Minolta RD-175 raw processing regression

### ISSUE THREAD

**Issue by LAK132** [Beep6581/RawTherapee#7328]
Switching to LlibRaw seems to break the processing of Minolta RD-175 raw files somehow.
Running a build of the dev branch (ba90c45f6b975d467b8c685d3a7ea8ba6220f3dc).

legacy:

![Image](https://github.com/user-attachments/assets/7e1297d3-3701-409f-a65d-6d633682eeec)

libraw:

![Image](https://github.com/user-attachments/assets/85746e82-58d7-40ae-b082-3cb108d5a9c1)

raw:

[0016.MDC](https://github.com/user-attachments/files/19089589/0016.MDC.txt)

**Comment by Lawrence37** [comment]
The white level is interpreted as 63 instead of 510 which makes the image 3 stops brighter.

**Comment by Lawrence37** [comment]
#7330 should fix it.

**Comment by LAK132** [comment]
that does seem to have fixed the white point in the main editor, however i am noticing the previews for photos that rawtherapee has previewed before are still wrong. looks like new photos are fine though, just thumbnail caching or something?

**Comment by Lawrence37** [comment]
Yes, you can clear the thumbnail cache with right click > Cache > Clear all except cached profiles. Then reload the folder.
