### ISSUE TITLE
Segfault since gtkmm stack upgrade

### ISSUE THREAD

**Issue by casta** [Beep6581/RawTherapee#7443]
**Short description**
Since gtkmm stack upgrade, rawtherapee segfault at startup. Not sure about the package that triggered the upgrade. But please see the stack trace below: I thing that there is an issue with default parameters. Patch proposal will follow.

**Steps to reproduce**
1. Update to gtkmm-3.24.10/pangomm-2.46.4/cairomm-1.14.5/atkmm-2.28.4/glibmm-2.66.8/libsigc++-2.12.1
2. Start rawtherapee, it’s segfault

**Expected behavior**
No segfault.

**Additional information**
Version: 5.12-8-g9f9b6ede8
Branch: dev
Commit: 9f9b6ede8
Commit date: 2025-06-15
Compiler: x86_64-pc-linux-gnu-gcc 15.1.0
Processor: 12th\ Gen\ Intel(R)\ Core(TM)\ i5-12500
System: Linux
Bit depth: 64 bits
Gtkmm: 3.24.10
Lensfun: 0.3.4.0
libjxl: Disabled
Build type: RelWithDebInfo
Build flags: -march=native -O3 -mtune=native -pipe -std=c++11 -ffp-contract=off  -Werror=unused-label -Werror=delete-incomplete -fno-math-errno -Wno-attributes -flto -Wall -Wuninitialized -Wcast-qual -Wno-deprecated-declarations -Wno-unused-result -Wunused-macros -fopenmp -Werror=unknown-pragmas  -ftree-vectorize
Link flags: -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,--sort-common  -flto
OpenMP support: yes
MMAP support: ON
Build OS: Linux 6.15.4-gentoo x86_64
Build date: Fri, 27 Jun 2025 19:03:13 +0000 UTC
Build epoch: 1751050993
Build UUID: 3284c1d5-6afc-46bb-ad79-90bbf656ccbd

Other useful information:
```

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6fd6c20 in Glib::ustring::ustring(Glib::ustring const&) () from /usr/lib64/libglibmm-2.4.so.1
(gdb) bt
#0  0x00007ffff6fd6c20 in Glib::ustring::ustring(Glib::ustring const&) () at /usr/lib64/libglibmm-2.4.so.1
#1  0x00005555560ff9c2 in rtengine::procparams::ColorManagementParams::ColorManagementParams (this=0x55555669bdb0 <rtengine::params+4400>, this=<optimized out>) at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/procparams.cc:2716
#2  0x0000555556114679 in rtengine::procparams::ProcParams::ProcParams (this=0x55555669ac80 <rtengine::params>, this=<optimized out>) at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/procparams.cc:6617
#3  0x0000555555858955 in _sub_I_65535_0.0 ()
#4  0x00007ffff52515ef in __libc_start_main () at /usr/lib64/libc.so.6
#5  0x000055555585a4a5 in _start ()
```

```
(gdb) p options.rtSettings
$1 = {iccDirectory = {static npos = 18446744073709551615, string_ = ""}, viewingdevice = 0, viewingdevicegrey = 0, viewinggreySc = 0, leveldnv = 0, leveldnti = 0, leveldnaut = 0, leveldnliss = 0, leveldnautsimpl = 0, printerProfile = {static npos = 18446744073709551615, string_ = ""}, printerIntent = 0, 
  printerBPC = false, monitorProfile = {static npos = 18446744073709551615, string_ = ""}, monitorIntent = 0, monitorBPC = false, autoMonitorProfile = false, autocielab = false, rgbcurveslumamode_gamut = false, verbose = false, darkFramesPath = {static npos = 18446744073709551615, string_ = ""}, flatFieldsPath = {
    static npos = 18446744073709551615, string_ = ""}, cameraProfilesPath = {static npos = 18446744073709551615, string_ = ""}, lensProfilesPath = {static npos = 18446744073709551615, string_ = ""}, enableLibRaw = false, adobe = {static npos = 18446744073709551615, string_ = ""}, prophoto = {
    static npos = 18446744073709551615, string_ = ""}, widegamut = {static npos = 18446744073709551615, string_ = ""}, beta = {static npos = 18446744073709551615, string_ = ""}, best = {static npos = 18446744073709551615, string_ = ""}, bruce = {static npos = 18446744073709551615, string_ = ""}, srgb = {
    static npos = 18446744073709551615, string_ = ""}, rec2020 = {static npos = 18446744073709551615, string_ = ""}, ACESp0 = {static npos = 18446744073709551615, string_ = ""}, JDCmax = {static npos = 18446744073709551615, string_ = ""}, ACESp1 = {static npos = 18446744073709551615, string_ = ""}, DCIP3 = {
    static npos = 18446744073709551615, string_ = ""}, gamutICC = false, gamutLch = false, HistogramWorking = false, amchroma = 0, amchromajz = 0, protectred = 0, protectredh = 0, nrauto = 0, nrautomax = 0, nrhigh = 0, nrwavlevel = 0, daubech = false, ciebadpixgauss = false, CRI_color = 0, denoiselabgamma = 0, 
  level0_cbdl = 0, level123_cbdl = 0, lensfunDbDirectory = {static npos = 18446744073709551615, string_ = ""}, lensfunDbBundleDirectory = {static npos = 18446744073709551615, string_ = ""}, cropsleep = 0, reduchigh = 0, reduclow = 0, detectshape = false, fftwsigma = false, previewselection = 0, cbdlsensi = 0, 
  itcwb_enable = false, itcwb_deltaspec = 0, itcwb_powponder = 0, basecorlog = 0, edghi = 0, edglo = 0, limrad = 0, thumbnail_inspector_mode = rtengine::Settings::ThumbnailInspectorMode::JPEG, xmp_sidecar_style = rtengine::Settings::XmpSidecarStyle::STD, metadata_xmp_sync = rtengine::Settings::MetadataXmpSync::NONE}
(gdb) p options.rtSettings.srgb
$2 = {static npos = 18446744073709551615, string_ = ""}
```

**Comment by casta** [comment]
This patch fixes the segfault.

Not sure about this, but for me the options.rtSettings struct is not correctly initialized here. Look at the stacktrace and the dump of the struct. This default settings should be hardcoded like the others just above.

```
--- a/rtengine/procparams.cc	2025-06-27 20:55:53.065487778 +0200
+++ b/rtengine/procparams.cc	2025-06-27 20:56:28.077191610 +0200
@@ -2713,7 +2713,7 @@
     labgridcieMx(0.),//
     labgridcieMy(0.),//
     aRendIntent(RI_RELATIVE),
-    outputProfile(options.rtSettings.srgb),
+    outputProfile("RTv4_sRGB"),
     outputIntent(RI_RELATIVE),
     outputBPC(true)
 {
```

**Comment by digitalcarp** [comment]
Can you try the patch in PR #7446 and let me know if it helps?

`git clone --single-branch -b empty_opts https://github.com/digitalcarp/RawTherapee.git`

**Comment by casta** [comment]
Sadly no, same thing.

New stacktrace:
```

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6fd6c20 in Glib::ustring::ustring(Glib::ustring const&) () from /usr/lib64/libglibmm-2.4.so.1
(gdb) bt
#0  0x00007ffff6fd6c20 in Glib::ustring::ustring(Glib::ustring const&) () at /usr/lib64/libglibmm-2.4.so.1
#1  0x0000555556102b82 in rtengine::procparams::ColorManagementParams::ColorManagementParams (this=0x55555669fdc0 <rtengine::params+4416>, this=<optimized out>) at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/procparams.cc:2721
#2  0x000055555611785c in rtengine::procparams::ProcParams::ProcParams (this=0x55555669ec80 <rtengine::params>, this=<optimized out>) at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/procparams.cc:6622
#3  0x0000555555856815 in _sub_I_65535_0.0 ()
#4  0x00007ffff52515ef in __libc_start_main () at /usr/lib64/libc.so.6
#5  0x0000555555858365 in _start ()
(gdb) up
#1  0x0000555556102b82 in rtengine::procparams::ColorManagementParams::ColorManagementParams (this=<optimized out>, this=<optimized out>) at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/procparams.cc:2721
warning: 2721   /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/procparams.cc: Aucun fichier ou dossier de ce nom
(gdb) p options.rtSettings
$1 = {iccDirectory = {static npos = 18446744073709551615, string_ = ""}, viewingdevice = 0, viewingdevicegrey = 0, viewinggreySc = 0, leveldnv = 0, leveldnti = 0, leveldnaut = 0, leveldnliss = 0, leveldnautsimpl = 0, printerProfile = {static npos = 18446744073709551615, string_ = ""}, printerIntent = 0, 
  printerBPC = false, monitorProfile = {static npos = 18446744073709551615, string_ = ""}, monitorIntent = 0, monitorBPC = false, autoMonitorProfile = false, autocielab = false, rgbcurveslumamode_gamut = false, verbose = false, darkFramesPath = {static npos = 18446744073709551615, string_ = ""}, flatFieldsPath = {
    static npos = 18446744073709551615, string_ = ""}, cameraProfilesPath = {static npos = 18446744073709551615, string_ = ""}, lensProfilesPath = {static npos = 18446744073709551615, string_ = ""}, enableLibRaw = false, adobe = {static npos = 18446744073709551615, string_ = ""}, prophoto = {
    static npos = 18446744073709551615, string_ = ""}, widegamut = {static npos = 18446744073709551615, string_ = ""}, beta = {static npos = 18446744073709551615, string_ = ""}, best = {static npos = 18446744073709551615, string_ = ""}, bruce = {static npos = 18446744073709551615, string_ = ""}, srgb = {
    static npos = 18446744073709551615, string_ = ""}, rec2020 = {static npos = 18446744073709551615, string_ = ""}, ACESp0 = {static npos = 18446744073709551615, string_ = ""}, JDCmax = {static npos = 18446744073709551615, string_ = ""}, ACESp1 = {static npos = 18446744073709551615, string_ = ""}, DCIP3 = {
    static npos = 18446744073709551615, string_ = ""}, gamutICC = false, gamutLch = false, HistogramWorking = false, amchroma = 0, amchromajz = 0, protectred = 0, protectredh = 0, nrauto = 0, nrautomax = 0, nrhigh = 0, nrwavlevel = 0, daubech = false, ciebadpixgauss = false, CRI_color = 0, denoiselabgamma = 0, 
  level0_cbdl = 0, level123_cbdl = 0, lensfunDbDirectory = {static npos = 18446744073709551615, string_ = ""}, lensfunDbBundleDirectory = {static npos = 18446744073709551615, string_ = ""}, cropsleep = 0, reduchigh = 0, reduclow = 0, detectshape = false, fftwsigma = false, previewselection = 0, cbdlsensi = 0, 
  itcwb_enable = false, itcwb_deltaspec = 0, itcwb_powponder = 0, basecorlog = 0, edghi = 0, edglo = 0, limrad = 0, thumbnail_inspector_mode = rtengine::Settings::ThumbnailInspectorMode::JPEG, xmp_sidecar_style = rtengine::Settings::XmpSidecarStyle::STD, metadata_xmp_sync = rtengine::Settings::MetadataXmpSync::NONE}
(gdb) 
```

I don’t get why it crashes with the empty string for colorspace since gtkmm upgrade. It’s beyond my old programming skills. My patch above still fixes it.

**Comment by digitalcarp** [comment]
The options struct should be a global variable initialized before main. The strings shouldn't be empty since they are hard-coded to certain values in `Options::setDefaults()` which is called in the constructor.

This might be some footgun with how global variables are initialized... I'll keep looking when I have time.

**Comment by Lawrence37** [comment]
In any case, it shouldn't crash with an empty string. The `Glib::ustring srgb` is perfectly valid and is ok to copy into `outputProfile`. I have the same library versions as you, but I don't get a crash. Have you done a clean build @casta?

**Comment by casta** [comment]
Yes, It’s always clean build: I build from source with gentoo package manager, not in the git repository directly.

By the way, the gtkmm stack upgrade is not the culprit: I downgraded everything to what I had some days ago (and did not segfault at this time), I now have the segfault at start too. So I do not understand why it did not segfault before and it does now… No other RT dependencies where upgraded, same gcc version, same compilation options.


I just disabled openmp in build, I now get a different stacktrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6fd6c20 in Glib::ustring::ustring(Glib::ustring const&) () from /usr/lib64/libglibmm-2.4.so.1
(gdb) bt
#0  0x00007ffff6fd6c20 in Glib::ustring::ustring(Glib::ustring const&) () at /usr/lib64/libglibmm-2.4.so.1
#1  0x00005555563421f2 in rtengine::procparams::ColorManagementParams::ColorManagementParams (this=this@entry=0x555556967ca0 <(anonymous namespace)::DEFAULT_CMP>) at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/procparams.cc:2721
#2  0x0000555555925fc4 in __static_initialization_and_destruction_0 () at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtgui/histogrampanel.cc:43
#3  _GLOBAL__sub_I__ZN13HistogramArea10MAX_BRIGHTE () at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtgui/histogrampanel.cc:1966
#4  0x00007ffff52515ef in __libc_start_main () at /usr/lib64/libc.so.6
#5  0x0000555555933f15 in _start ()
(gdb) up
#1  0x00005555563421f2 in rtengine::procparams::ColorManagementParams::ColorManagementParams (this=this@entry=0x555556967ca0 <(anonymous namespace)::DEFAULT_CMP>) at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/procparams.cc:2721
warning: 2721   /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/procparams.cc: Aucun fichier ou dossier de ce nom
(gdb) p options.rtSettings
$1 = {iccDirectory = {static npos = 18446744073709551615, string_ = ""}, viewingdevice = 0, viewingdevicegrey = 0, viewinggreySc = 0, leveldnv = 0, leveldnti = 0, leveldnaut = 0, leveldnliss = 0, leveldnautsimpl = 0, printerProfile = {static npos = 18446744073709551615, string_ = ""}, printerIntent = 0, 
  printerBPC = false, monitorProfile = {static npos = 18446744073709551615, string_ = ""}, monitorIntent = 0, monitorBPC = false, autoMonitorProfile = false, autocielab = false, rgbcurveslumamode_gamut = false, verbose = false, darkFramesPath = {static npos = 18446744073709551615, string_ = ""}, flatFieldsPath = {
    static npos = 18446744073709551615, string_ = ""}, cameraProfilesPath = {static npos = 18446744073709551615, string_ = ""}, lensProfilesPath = {static npos = 18446744073709551615, string_ = ""}, enableLibRaw = false, adobe = {static npos = 18446744073709551615, string_ = ""}, prophoto = {
    static npos = 18446744073709551615, string_ = ""}, widegamut = {static npos = 18446744073709551615, string_ = ""}, beta = {static npos = 18446744073709551615, string_ = ""}, best = {static npos = 18446744073709551615, string_ = ""}, bruce = {static npos = 18446744073709551615, string_ = ""}, srgb = {
    static npos = 18446744073709551615, string_ = ""}, rec2020 = {static npos = 18446744073709551615, string_ = ""}, ACESp0 = {static npos = 18446744073709551615, string_ = ""}, JDCmax = {static npos = 18446744073709551615, string_ = ""}, ACESp1 = {static npos = 18446744073709551615, string_ = ""}, DCIP3 = {
    static npos = 18446744073709551615, string_ = ""}, gamutICC = false, gamutLch = false, HistogramWorking = false, amchroma = 0, amchromajz = 0, protectred = 0, protectredh = 0, nrauto = 0, nrautomax = 0, nrhigh = 0, nrwavlevel = 0, daubech = false, ciebadpixgauss = false, CRI_color = 0, denoiselabgamma = 0, 
  level0_cbdl = 0, level123_cbdl = 0, lensfunDbDirectory = {static npos = 18446744073709551615, string_ = ""}, lensfunDbBundleDirectory = {static npos = 18446744073709551615, string_ = ""}, cropsleep = 0, reduchigh = 0, reduclow = 0, detectshape = false, fftwsigma = false, previewselection = 0, cbdlsensi = 0, 
  itcwb_enable = false, itcwb_deltaspec = 0, itcwb_powponder = 0, basecorlog = 0, edghi = 0, edglo = 0, limrad = 0, thumbnail_inspector_mode = rtengine::Settings::ThumbnailInspectorMode::JPEG, xmp_sidecar_style = rtengine::Settings::XmpSidecarStyle::STD, metadata_xmp_sync = rtengine::Settings::MetadataXmpSync::NONE}
(gdb) up
#2  0x0000555555925fc4 in __static_initialization_and_destruction_0 () at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtgui/histogrampanel.cc:43
warning: 43     /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtgui/histogrampanel.cc: Aucun fichier ou dossier de ce nom
(gdb) p  DEFAULT_CMP
$1 = {inputProfile = {static npos = 18446744073709551615, string_ = "(cameraICC)"}, toneCurve = false, applyLookTable = false, applyBaselineExposureOffset = true, applyHueSatMap = true, dcpIlluminant = 0, workingProfile = {static npos = 18446744073709551615, string_ = "ProPhoto"}, 
  workingTRC = rtengine::procparams::ColorManagementParams::WorkingTrc::NONE, will = rtengine::procparams::ColorManagementParams::Illuminant::DEFAULT, wprim = rtengine::procparams::ColorManagementParams::Primaries::DEFAULT, wcat = rtengine::procparams::ColorManagementParams::Cat::BRAD, wGamma = 2.3999999999999999, 
  wSlope = 12.92, wmidtcie = 0, sigmatrc = 1, offstrc = 1, residtrc = 0, pyrwavtrc = 2, opacityCurveWLI = std::vector of length 13, capacity 13 = {1, 0, 0.5, 0.34999999999999998, 0.34999999999999998, 0.5, 0.69999999999999996, 0.34999999999999998, 0.34999999999999998, 1, 0.5, 0.34999999999999998, 
    0.34999999999999998}, wsmoothcie = false, redx = 0.73470000000000002, redy = 0.26529999999999998, grex = 0.15959999999999999, grey = 0.84040000000000004, blux = 0.036600000000000001, bluy = 0.0001, refi = 0, shiftx = 0, shifty = 0, preser = 0, fbw = false, trcExp = false, wavExp = false, gamut = true, 
  labgridcieALow = 0.51763000000000003, labgridcieBLow = -0.33582000000000001, labgridcieAHigh = -0.75163000000000002, labgridcieBHigh = -0.81799999999999995, labgridcieGx = -0.69164000000000003, labgridcieGy = -0.70909, labgridcieWx = -0.18964, labgridcieWy = -0.16636000000000001, labgridcieMx = 0, 
  labgridcieMy = 0, aRendIntent = rtengine::RI_RELATIVE, outputProfile = {static npos = 18446744073709551615, string_ = ""}, outputIntent = rtengine::RI_PERCEPTUAL, outputBPC = false}
```
 
Is there something that help you here?

**Comment by Lawrence37** [comment]
It's strange that it suddenly stopped working. I can't reproduce the issue, so could you try a few things and report the behavior?
- Try a different language. If you had it set to use the system language, you can launch it with the `LANG` environment variable set to something else, like `en_US` for US English and `fr_FR` for French. Otherwise, you'll have to edit the language in the `options` file.
- Reset your `options` file. Simply renaming it will work. Then you will also have a copy of the original if you want to restore the settings.
- Edit the code so that `outputProfile` is set to `""`.
- Edit the code so that `srgb` is explicitly set to `"RTv4_sRGB"` or `""`.

**Comment by digitalcarp** [comment]
I see `_sub_I_65535_0.0` in the original stack trace and `_GLOBAL__sub_I__ZN13HistogramArea10MAX_BRIGHTE` + `__static_initialization_and_destruction_0` in the new stack trace. Both seem to be indicating something with global/static initialization.

As another sanity check, can you try compiling without LTO?

Thanks for trying these experiments as I can't reproduce the crash.

**Comment by casta** [comment]
> It's strange that it suddenly stopped working. I can't reproduce the issue, so could you try a few things and report the behavior?
> 
>     * Try a different language. If you had it set to use the system language, you can launch it with the `LANG` environment variable set to something else, like `en_US` for US English and `fr_FR` for French. Otherwise, you'll have to edit the language in the `options` file.
> 
>     * Reset your `options` file. Simply renaming it will work. Then you will also have a copy of the original if you want to restore the settings.

Same crash with both of those tests

>     * Edit the code so that `outputProfile` is set to `""`.

This one fixes the crash.

>     * Edit the code so that `srgb` is explicitly set to `"RTv4_sRGB"` or `""`.

I’m not sure where I should do this?


@digitalcarp: LTO is already disabled since I produced debug builds. Same segfault with O2.


I tried to build RT with clang-20. The stack trace is a bit different, but segfault in the same location:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6fd6c20 in Glib::ustring::ustring(Glib::ustring const&) () from /usr/lib64/libglibmm-2.4.so.1
(gdb) bt
#0  0x00007ffff6fd6c20 in Glib::ustring::ustring(Glib::ustring const&) () at /usr/lib64/libglibmm-2.4.so.1
#1  0x00005555561730cf in rtengine::procparams::ColorManagementParams::ColorManagementParams (this=0x5555567995b0 <(anonymous namespace)::DEFAULT_CMP>) at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/procparams.cc:2721
#2  0x00005555557c8774 in __cxx_global_var_init () at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtgui/histogrampanel.cc:43
#3  0x00005555557c8774 in _GLOBAL__sub_I_histogrampanel.cc ()
#4  0x00007ffff52515ef in __libc_start_main () at /usr/lib64/libc.so.6
#5  0x00005555557d6315 in _start ()
```

**Comment by Lawrence37** [comment]
You can set `srgb` by changing this line.
https://github.com/RawTherapee/RawTherapee/blob/1732e96eee64e68a052efb6129abcaedb5527363/rtengine/settings.h#L62
` Glib::ustring   srgb = "RTv4_sRGB";`

**Comment by casta** [comment]
Same segfault with this change.


If it’s of any help, I run valgrind, but I do not see new information here:
```
$ valgrind rawtherapee
==629832== Memcheck, a memory error detector
==629832== Copyright (C) 2002-2024, and GNU GPL'd, by Julian Seward et al.
==629832== Using Valgrind-3.25.1 and LibVEX; rerun with -h for copyright info
==629832== Command: rawtherapee
==629832== 
==629832== Invalid read of size 1
==629832==    at 0x6E4FC20: Glib::ustring::ustring(Glib::ustring const&) (in /usr/lib64/libglibmm-2.4.so.1.3.0)
==629832==    by 0x4DEE1F1: rtengine::procparams::ColorManagementParams::ColorManagementParams() (procparams.cc:2721)
==629832==    by 0x43D1FC3: __static_initialization_and_destruction_0 (histogrampanel.cc:43)
==629832==    by 0x43D1FC3: _GLOBAL__sub_I__ZN13HistogramArea10MAX_BRIGHTE (histogrampanel.cc:1966)
==629832==    by 0x86C95EE: (below main) (in /usr/lib64/libc.so.6)
==629832==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==629832== 
==629832== 
==629832== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==629832==  Access not within mapped region at address 0x0
==629832==    at 0x6E4FC20: Glib::ustring::ustring(Glib::ustring const&) (in /usr/lib64/libglibmm-2.4.so.1.3.0)
==629832==    by 0x4DEE1F1: rtengine::procparams::ColorManagementParams::ColorManagementParams() (procparams.cc:2721)
==629832==    by 0x43D1FC3: __static_initialization_and_destruction_0 (histogrampanel.cc:43)
==629832==    by 0x43D1FC3: _GLOBAL__sub_I__ZN13HistogramArea10MAX_BRIGHTE (histogrampanel.cc:1966)
==629832==    by 0x86C95EE: (below main) (in /usr/lib64/libc.so.6)
==629832==  If you believe this happened as a result of a stack
==629832==  overflow in your program's main thread (unlikely but
==629832==  possible), you can try to increase the size of the
==629832==  main thread stack using the --main-stacksize= flag.
==629832==  The main thread stack size used in this run was 8388608.
==629832== 
==629832== HEAP SUMMARY:
==629832==     in use at exit: 191,228 bytes in 1,574 blocks
==629832==   total heap usage: 1,978 allocs, 404 frees, 212,877 bytes allocated
==629832== 
==629832== LEAK SUMMARY:
==629832==    definitely lost: 0 bytes in 0 blocks
==629832==    indirectly lost: 0 bytes in 0 blocks
==629832==      possibly lost: 0 bytes in 0 blocks
==629832==    still reachable: 189,380 bytes in 1,553 blocks
==629832==         suppressed: 0 bytes in 0 blocks
==629832== Rerun with --leak-check=full to see details of leaked memory
==629832== 
==629832== For lists of detected and suppressed errors, rerun with: -s
==629832== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Erreur de segmentation (core dumped)
```

**Comment by Floessie** [comment]
AFAIK there's no guaranteed initialization order for global (static) variables. This is why globals are better avoided. Here we have two globals which depend on each other: `options` in  `rtgui/options.cc:59` and `DEFAULT_CMP` in `rtgui/histogrampanel.cc:43`. One of them has to go, IMHO the latter. It could be moved to the point where it is needed and turned into a `static const` at that place, which is initialized once on the first call.

Best,
Flössie

**Comment by digitalcarp** [comment]
Can you try the patch again in PR #7446? I pushed a fix that replaces all `DEFAULT_CMP` globals with a Meyer's singleton.

`git clone --single-branch -b empty_opts https://github.com/digitalcarp/RawTherapee.git`

**Comment by casta** [comment]
Thank you, very good progress! It works correctly **without** LTO.

But with LTO, I still get a segfault, with a different stacktrace than before:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6fd6c20 in Glib::ustring::ustring(Glib::ustring const&) () from /usr/lib64/libglibmm-2.4.so.1
(gdb) bt
#0  0x00007ffff6fd6c20 in Glib::ustring::ustring(Glib::ustring const&) () at /usr/lib64/libglibmm-2.4.so.1
#1  0x00005555560d2942 in rtengine::procparams::ColorManagementParams::ColorManagementParams (this=0x555556650a20 <rtengine::params+4416>, this=<optimized out>) at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/procparams.cc:2727
#2  0x00005555560e655c in rtengine::procparams::ProcParams::ProcParams (this=0x55555664f8e0 <rtengine::params>, this=<optimized out>) at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/procparams.cc:6628
#3  0x00005555558579b5 in _sub_I_65535_0.0 ()
#4  0x00007ffff52515ef in __libc_start_main () at /usr/lib64/libc.so.6
#5  0x0000555555859485 in _start ()
```

**Comment by digitalcarp** [comment]
Probably need to change `extern Options options;` into `Options& Options::get()` as well? A rather noisy change, so maybe I'll test it in a separate branch.

**Comment by digitalcarp** [comment]
Can you try:

`git clone --single-branch -b meyers https://github.com/digitalcarp/RawTherapee.git`

**Comment by casta** [comment]
Hello,

I had to apply this change to make the build pass without BUILD_BUNDLE:

```
diff --git a/rtgui/main.cc b/rtgui/main.cc
index 76557e1a1..53302a457 100644
--- a/rtgui/main.cc
+++ b/rtgui/main.cc
@@ -357,6 +357,8 @@ int main (int argc, char **argv)
     }
 #endif
 
+    auto& app = App::get();
+
 #ifdef BUILD_BUNDLE
     char exname[512] = {0};
     Glib::ustring exePath;
@@ -374,8 +376,6 @@ int main (int argc, char **argv)
 #endif
     exePath = Glib::path_get_dirname (exname);
 
-    auto& app = App::get();
-
     // set paths
     if (Glib::path_is_absolute (DATA_SEARCH_PATH)) {
         app.setArgv0(DATA_SEARCH_PATH);
```


After that, I get a 
```
terminate called after throwing an instance of '__gnu_cxx::recursive_init_error'
  what():  std::exception
```


without LTO:
```
(gdb) bt
#0  0x00007ffff52bf3ac in ??? () at /usr/lib64/libc.so.6
#1  0x00007ffff52672c6 in raise () at /usr/lib64/libc.so.6
#2  0x00007ffff524f30b in abort () at /usr/lib64/libc.so.6
#3  0x00007ffff54ab009 in ??? () at /usr/lib/gcc/x86_64-pc-linux-gnu/15/libstdc++.so.6
#4  0x00007ffff54c1dfc in ??? () at /usr/lib/gcc/x86_64-pc-linux-gnu/15/libstdc++.so.6
#5  0x00007ffff54aa873 in __cxa_call_terminate () at /usr/lib/gcc/x86_64-pc-linux-gnu/15/libstdc++.so.6
#6  0x00007ffff54c1632 in __gxx_personality_v0 () at /usr/lib/gcc/x86_64-pc-linux-gnu/15/libstdc++.so.6
#7  0x00007ffff62badde in ??? () at /usr/lib/gcc/x86_64-pc-linux-gnu/15/libgcc_s.so.1
#8  0x00007ffff62bb499 in _Unwind_RaiseException () at /usr/lib/gcc/x86_64-pc-linux-gnu/15/libgcc_s.so.1
#9  0x00007ffff54c209a in __cxa_throw () at /usr/lib/gcc/x86_64-pc-linux-gnu/15/libstdc++.so.6
#10 0x00007ffff54aaa3c in ??? () at /usr/lib/gcc/x86_64-pc-linux-gnu/15/libstdc++.so.6
#11 0x00005555564b84c1 in App::get () at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/rtapp.cc:34
#12 0x0000555556379da6 in rtengine::procparams::ColorManagementParams::ColorManagementParams (this=this@entry=0x555556a06fc0) at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/procparams.cc:2721
#13 0x00005555564b8404 in App::App (this=0x5555569c7480 <App::get()::inst>) at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/rtapp.cc:40
#14 0x00005555564b84e5 in App::get () at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/rtapp.cc:34
#15 0x0000555556379da6 in rtengine::procparams::ColorManagementParams::ColorManagementParams (this=0x5555569c89c0 <rtengine::params+4416>) at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/procparams.cc:2721
#16 0x00005555563ee527 in rtengine::procparams::ProcParams::ProcParams (this=this@entry=0x5555569c7880 <rtengine::params>) at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/procparams.cc:6624
#17 0x0000555555930fd4 in __static_initialization_and_destruction_0 () at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/hilite_recon.cc:301
#18 _GLOBAL__sub_I__ZN8rtengine14RawImageSource18HLRecovery_inpaintEPPfS2_S2_i () at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/hilite_recon.cc:1596
#19 0x00007ffff52515ef in __libc_start_main () at /usr/lib64/libc.so.6
#20 0x0000555555931025 in _start ()

```

With LTO:
```
(gdb) bt
#0  0x00007ffff52bf3ac in ??? () at /usr/lib64/libc.so.6
#1  0x00007ffff52672c6 in raise () at /usr/lib64/libc.so.6
#2  0x00007ffff524f30b in abort () at /usr/lib64/libc.so.6
#3  0x00007ffff54ab009 in ??? () at /usr/lib/gcc/x86_64-pc-linux-gnu/15/libstdc++.so.6
#4  0x00007ffff54c1dfc in ??? () at /usr/lib/gcc/x86_64-pc-linux-gnu/15/libstdc++.so.6
#5  0x00007ffff54aa9f4 in std::terminate() () at /usr/lib/gcc/x86_64-pc-linux-gnu/15/libstdc++.so.6
#6  0x00007ffff54c20a7 in __cxa_throw () at /usr/lib/gcc/x86_64-pc-linux-gnu/15/libstdc++.so.6
#7  0x00007ffff54aaa3c in ??? () at /usr/lib/gcc/x86_64-pc-linux-gnu/15/libstdc++.so.6
#8  0x0000555556274bd1 in App::get () at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/rtapp.cc:34
#9  0x00005555561050f6 in rtengine::procparams::ColorManagementParams::ColorManagementParams (this=0x5555566d4f40, this=<optimized out>) at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/procparams.cc:2721
#10 0x0000555556274c49 in App::App (this=<optimized out>) at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/rtapp.cc:40
#11 App::get () at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/rtapp.cc:34
#12 0x00005555561050f6 in rtengine::procparams::ColorManagementParams::ColorManagementParams (this=0x55555669e8a0 <rtengine::params+4416>, this=<optimized out>) at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/procparams.cc:2721
#13 0x0000555556119e1c in rtengine::procparams::ProcParams::ProcParams (this=0x55555669d760 <rtengine::params>, this=<optimized out>) at /var/tmp/portage/media-gfx/rawtherapee-9999/work/rawtherapee-9999/rtengine/procparams.cc:6624
#14 0x0000555555857d55 in _sub_I_65535_0.0 ()
#15 0x00007ffff52515ef in __libc_start_main () at /usr/lib64/libc.so.6
#16 0x0000555555859785 in _start ()
```


Thank’s for your work here!

**Comment by digitalcarp** [comment]
Oh some silly mistakes by me. Please try again with the updated `meyers` branch.

**Comment by casta** [comment]
Thank you VERY MUCH !

It’s now working nicely with and without LTO :)

**Comment by rzsn** [comment]
Has anybody from my Gentoo friends above have a file I can drop to _/etc/portage/patches_ for the _media-gfx/rawtherapee-5.12::gentoo_ to be fixed?

I likely run to the same issue:

`[140613.955852] rawtherapee[1182]: segfault at 0 ip 00007f5d6f1f3cc0 sp 00007ffff07add70 error 4 in libglibmm-2.4.so.1.3.0[6fcc0,7f5d6f1c1000+3c000] likely on CPU 8 (core 16, socket 0)`

and only dev-cpp/glibmm has a DEBUG use flag, so my attempts (without digging into custom builds) end up at:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6fd4e00 in Glib::ustring::ustring(Glib::ustring const&) () from /usr/lib64/libglibmm-2.4.so.1
(gdb) bt
#0  0x00007ffff6fd4e00 in Glib::ustring::ustring(Glib::ustring const&) () at /usr/lib64/libglibmm-2.4.so.1
#1  0x00005555561a6f72 in ??? ()
#2  0x00005555558929b4 in ??? ()
#3  0x00007ffff559d58f in __libc_start_main () at /usr/lib64/libc.so.6
#4  0x000055555589f375 in ??? ()
```

**Comment by phototeacher94-tech** [comment]
I've read this thread and it's way over my head. Sorry. I double click as instructed, then drop and drag the little icon into the Application folder. It asks if I want to open or Show Disk Image. I've tried both without any luck; still get the garbled mess in the screenshot. It also shows up in the bar at the bottom but just bounces and then never opens. 

<img width="897" height="632" alt="Image" src="https://github.com/user-attachments/assets/17d6c24a-0187-466a-878d-f3c193dbdb0b" />

This is a screenshot of what I'm getting.

**Comment by digitalcarp** [comment]
@rzsn I opened a PR to backport the fix to release-5.12 branch. There's also a patch file available at:

https://github.com/digitalcarp/RawTherapee/blob/meyer-5.12/patch/0001-Fix-static-init-order-fiasco-crashes.patch

Can you try testing applying the patch and seeing if RawTherapee works as expected?

**Comment by rzsn** [comment]
@digitalcarp - I have saved the linked _0001-Fix-static-init-order-fiasco-crashes.patch_ file to _/etc/portage/patches/media-gfx/rawtherapee-5.12_ and re-emerged the rawtherapee. During the initial phase, the user patch applies cleanly, and after it is compiled and installed - the rawtherapee runs again, on GCC-15 profile.

So.. pure perfection! Thanks a lot!
